import type { DomainSeed, ObjectCategorySeed, SystemSeed } from './types';

/**
 * DOMAIN -> OBJECT -> SYSTEM.
 *
 * Note what is NOT here: a "Life" level above Mobility. Every problem on this
 * site is a life problem, so the word carries no information and would earn no
 * URL segment, no useful hub and no clarity for a crawler. The taxonomy starts
 * where the first genuine distinction is.
 *
 * `status: 'draft'` means "named, reserved, not built". Draft nodes are not
 * routable and never enter the sitemap; hubs list them as plain text so the site
 * shows its real size instead of a wall of empty category pages.
 *
 * `indexable` is separate from `status` on purpose. A hub can be live and
 * linkable for humans while still being too thin to deserve a place in search
 * results. Flip it to true once the hub actually helps a searcher.
 */

export const domains: DomainSeed[] = [
  {
    slug: 'mobility',
    name: 'Mobility',
    canonicalPath: '/mobility/',
    shortDescription: 'Cars, motorcycles, bikes — anything you use to get around.',
    hubHeading: 'Mobility Problems: What Can You Ignore?',
    seoTitle: 'Mobility Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the car, motorcycle and bike problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 10,
    status: 'published',
    // One published problem beneath it. Not yet a page worth ranking.
    indexable: false,
  },
  // Reserved top-level domains. Named so the shape of the site is visible, drafts
  // so none of them becomes an empty indexed page.
  {
    slug: 'home',
    name: 'Home',
    canonicalPath: '/home/',
    shortDescription: 'Plumbing, electrical, HVAC, roof, structure.',
    hubHeading: 'Home Problems: What Can You Ignore?',
    seoTitle: 'Home Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the household plumbing and electrical problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'appliances',
    name: 'Appliances',
    canonicalPath: '/appliances/',
    shortDescription: 'Fridges, dishwashers, washers, dryers, coffee machines.',
    sortOrder: 30,
    status: 'draft',
    indexable: false,
  },
  {
    slug: 'food-kitchen',
    name: 'Food & Kitchen',
    canonicalPath: '/food-kitchen/',
    shortDescription: 'Food storage, freezer and refrigerator safety.',
    hubHeading: 'Food & Kitchen: What Can You Ignore?',
    seoTitle: 'Food & Kitchen: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on food-storage and refrigeration questions — what is still safe to eat, what to check first, and what to throw out.',
    sortOrder: 35,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'tech',
    name: 'Technology',
    canonicalPath: '/technology/',
    shortDescription: 'Computers, phones, routers, storage, updates.',
    hubHeading: 'Technology Problems: What Can You Ignore?',
    seoTitle: 'Technology Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on phone and computer problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'garden-and-outdoors',
    name: 'Garden & Outdoors',
    canonicalPath: '/garden-and-outdoors/',
    shortDescription: 'Lawn, trees, plants, pools, outdoor equipment.',
    sortOrder: 50,
    status: 'draft',
    indexable: false,
  },
  {
    slug: 'personal-gear',
    name: 'Personal Gear',
    canonicalPath: '/personal-gear/',
    shortDescription: 'Shoes, watches, cameras, sports and outdoor kit.',
    sortOrder: 60,
    status: 'draft',
    indexable: false,
  },
];

export const objectCategories: ObjectCategorySeed[] = [
  {
    domainSlug: 'mobility',
    slug: 'cars',
    name: 'Cars',
    singularName: 'Car',
    // Deliberately NOT /mobility/cars/. Mobility is a useful hub and a useful
    // breadcrumb; it is not a useful URL segment.
    canonicalPath: '/cars/',
    shortDescription: 'Warning lights, noises, leaks and the maintenance you have been putting off.',
    hubHeading: 'Car Problems: What Can You Ignore?',
    seoTitle: 'Car Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Straight verdicts on common car problems. Find out which ones can wait, which ones cannot, and what actually happens if you keep driving.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'motorcycles',
    name: 'Motorcycles',
    canonicalPath: '/motorcycles/',
    shortDescription: 'Chain, tires, brakes, fluids.',
    sortOrder: 20,
    status: 'draft',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'bicycles',
    name: 'Bicycles',
    singularName: 'Bike',
    canonicalPath: '/bicycles/',
    shortDescription: 'Helmets, drivetrain, brakes, tires, bearings.',
    hubHeading: 'Bike Problems: What Can You Ignore?',
    seoTitle: 'Bike Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Bicycle problems sorted by how urgent they actually are — starting with the safety gear, where the answer is rarely a matter of opinion.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'e-bikes-and-scooters',
    name: 'E-bikes & Scooters',
    canonicalPath: '/e-bikes-and-scooters/',
    shortDescription: 'Batteries, motors, brakes, firmware.',
    sortOrder: 40,
    status: 'draft',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'plumbing',
    name: 'Plumbing',
    singularName: 'Plumbing',
    canonicalPath: '/home/plumbing/',
    shortDescription: 'Drains, toilets, leaks, water pressure.',
    hubHeading: 'Plumbing Problems: What Can You Ignore?',
    seoTitle: 'Plumbing Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household plumbing problems sorted by how urgent they actually are — from a slow drain you can watch to leaks that need attention now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'electrical',
    name: 'Electrical',
    singularName: 'Electrical',
    canonicalPath: '/home/electrical/',
    shortDescription: 'Outlets, switches, lighting, wiring.',
    hubHeading: 'Electrical Problems: What Can You Ignore?',
    seoTitle: 'Electrical Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household electrical problems sorted by how urgent they actually are — from a flickering light you can watch to warning signs that need an electrician now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'safety',
    name: 'Home Safety',
    singularName: 'Home Safety',
    canonicalPath: '/home/safety/',
    shortDescription: 'Smoke and CO alarms, extinguishers, detectors.',
    hubHeading: 'Home Safety: What Can You Ignore?',
    seoTitle: 'Home Safety Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Home safety-device problems sorted by how urgent they actually are — from a chirping smoke alarm to alarm patterns that mean get out now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'structure',
    name: 'Structure',
    singularName: 'Structure',
    canonicalPath: '/home/structure/',
    shortDescription: 'Windows, walls, damp and rot.',
    hubHeading: 'Home Structure: What Can You Ignore?',
    seoTitle: 'Window and Damp Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Window and damp problems sorted by how urgent they actually are — starting with the mold that shows up on a frame every winter.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'food-kitchen',
    slug: 'food-storage',
    name: 'Food Storage',
    singularName: 'Food Storage',
    canonicalPath: '/food-kitchen/food-storage/',
    shortDescription: 'Freezer burn, expiration, spoilage signs.',
    hubHeading: 'Food Storage: What Can You Ignore?',
    seoTitle: 'Food Storage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Food-storage questions sorted by how urgent they actually are — from freezer burn you can ignore to spoilage signs that mean throw it out.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'food-kitchen',
    slug: 'refrigeration',
    name: 'Refrigeration',
    singularName: 'Refrigeration',
    canonicalPath: '/food-kitchen/refrigeration/',
    shortDescription: 'Temperature, power loss, food safety after a fridge problem.',
    hubHeading: 'Refrigeration Problems: What Can You Ignore?',
    seoTitle: 'Refrigeration Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator and freezer questions sorted by how urgent they actually are — from a brief door-open mishap to food that needs to be discarded.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'phones',
    name: 'Phones',
    singularName: 'Phone',
    canonicalPath: '/technology/phones/',
    shortDescription: 'Screens, batteries, charging, water damage.',
    hubHeading: 'Phone Problems: What Can You Ignore?',
    seoTitle: 'Phone Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone problems sorted by how urgent they actually are — from a small screen crack you can watch to damage that means stop using it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'computers',
    name: 'Computers',
    singularName: 'Computer',
    canonicalPath: '/technology/computers/',
    shortDescription: 'Batteries, chargers, overheating, performance.',
    hubHeading: 'Computer Problems: What Can You Ignore?',
    seoTitle: 'Computer Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop and computer problems sorted by how urgent they actually are — from a warm charger you can ignore to a battery that means stop using it.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
];

/**
 * The System level is what stops a large site collapsing. Fifty problems can sit
 * directly under "Cars" and still be navigable; five hundred cannot.
 */
export const systems: SystemSeed[] = [
  {
    objectSlug: 'cars',
    slug: 'tires',
    name: 'Tires',
    singularName: 'Tire',
    canonicalPath: '/cars/tires/',
    shortDescription: 'Pressure, wear, punctures, age and damage.',
    hubHeading: 'Can I Ignore These Tire Problems?',
    seoTitle: 'Tire Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Tire problems sorted by how urgent they actually are — from the ones you can leave a while to the ones that mean stop driving.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'exhaust',
    name: 'Exhaust',
    singularName: 'Exhaust',
    canonicalPath: '/cars/exhaust/',
    shortDescription: 'Noise, smell, emissions, corrosion.',
    hubHeading: 'Can I Ignore These Exhaust Problems?',
    seoTitle: 'Exhaust Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Exhaust problems sorted by how urgent they actually are — from normal condensation you can ignore to leaks and warning signs that need attention.',
    sortOrder: 100,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'engine',
    name: 'Engine',
    singularName: 'Engine',
    canonicalPath: '/cars/engine/',
    shortDescription: 'Warning lights, oil, noises, misfires.',
    hubHeading: 'Can I Ignore These Engine Problems?',
    seoTitle: 'Engine Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Engine problems sorted by how urgent they actually are — from normal cold-start behavior you can ignore to warning signs that need attention.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'brakes',
    name: 'Brakes',
    singularName: 'Brake',
    canonicalPath: '/cars/brakes/',
    shortDescription: 'Pads, discs, fluid, noises.',
    hubHeading: 'Can I Ignore These Brake Problems?',
    seoTitle: 'Brake Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Brake problems sorted by how urgent they actually are — from harmless noise you can ignore to warning signs that need attention.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'fluids',
    name: 'Fluids',
    singularName: 'Fluid',
    canonicalPath: '/cars/fluids/',
    shortDescription: 'Oil, coolant, brake, transmission, washer.',
    hubHeading: 'Can I Ignore These Fluid Problems?',
    seoTitle: 'Fluid Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Car fluid problems sorted by how urgent they actually are — from a small drip you can watch to leaks and warnings that need attention.',
    sortOrder: 60,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'glass',
    name: 'Glass',
    singularName: 'Glass',
    canonicalPath: '/cars/glass/',
    shortDescription: 'Chips, cracks, wipers, visibility.',
    hubHeading: 'Can I Ignore These Glass Problems?',
    seoTitle: 'Glass Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Car glass problems sorted by how urgent they actually are — from a small chip you can watch to cracks and damage that need attention.',
    sortOrder: 120,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'bicycles',
    slug: 'helmets',
    name: 'Helmets',
    singularName: 'Helmet',
    canonicalPath: '/bicycles/helmets/',
    shortDescription: 'Crash damage, cracks, age, fit and straps.',
    hubHeading: 'Can I Ignore These Helmet Problems?',
    seoTitle: 'Bike Helmet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Bike helmet questions sorted by how urgent they are — from a scuffed shell that is fine to damage that means the helmet is finished.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'drains',
    name: 'Drains',
    singularName: 'Drain',
    canonicalPath: '/home/plumbing/drains/',
    shortDescription: 'Slow drains, clogs, gurgling, backups.',
    hubHeading: 'Can I Ignore These Drain Problems?',
    seoTitle: 'Drain Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Drain problems sorted by how urgent they actually are — from a slightly slow sink to a sewer backup that needs a plumber now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'toilets',
    name: 'Toilets',
    singularName: 'Toilet',
    canonicalPath: '/home/plumbing/toilets/',
    shortDescription: 'Running toilets, clogs, leaks, flushing problems.',
    hubHeading: 'Can I Ignore These Toilet Problems?',
    seoTitle: 'Toilet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Toilet problems sorted by how urgent they actually are — from a briefly running tank to a bowl that is about to overflow.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'leaks',
    name: 'Leaks',
    singularName: 'Leak',
    canonicalPath: '/home/plumbing/leaks/',
    shortDescription: 'Under-sink leaks, pipe leaks, water damage.',
    hubHeading: 'Can I Ignore These Leaks?',
    seoTitle: 'Plumbing Leaks: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household leaks sorted by how urgent they actually are — from a drip you can watch to a supply line that needs the water shut off now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'lighting',
    name: 'Lighting',
    singularName: 'Light',
    canonicalPath: '/home/electrical/lighting/',
    shortDescription: 'Flickering, bulbs, switches, fixtures.',
    hubHeading: 'Can I Ignore These Lighting Problems?',
    seoTitle: 'Lighting Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Lighting problems sorted by how urgent they actually are — from a flickering bulb to wiring warning signs that need an electrician.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'outlets',
    name: 'Outlets',
    singularName: 'Outlet',
    canonicalPath: '/home/electrical/outlets/',
    shortDescription: 'Warm outlets, loose plugs, sparking, wiring.',
    hubHeading: 'Can I Ignore These Outlet Problems?',
    seoTitle: 'Outlet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Electrical outlet problems sorted by how urgent they actually are — from a mildly warm plug to a receptacle that needs to stay unused.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'safety',
    slug: 'alarms',
    name: 'Alarms',
    singularName: 'Alarm',
    canonicalPath: '/home/safety/alarms/',
    shortDescription: 'Smoke alarms, CO alarms, chirps and false alarms.',
    hubHeading: 'Can I Ignore These Alarm Problems?',
    seoTitle: 'Smoke and CO Alarm Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Smoke and carbon monoxide alarm problems sorted by how urgent they are — from a low-battery chirp to the patterns that mean leave the house.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'windows',
    name: 'Windows',
    singularName: 'Window',
    canonicalPath: '/home/structure/windows/',
    shortDescription: 'Condensation, mold, drafts, rotten frames.',
    hubHeading: 'Can I Ignore These Window Problems?',
    seoTitle: 'Window Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Window problems sorted by how urgent they actually are — from winter condensation to mold and rot that has reached the wall behind the frame.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'phones',
    slug: 'screens',
    name: 'Screens',
    singularName: 'Screen',
    canonicalPath: '/technology/phones/screens/',
    shortDescription: 'Cracked glass, display damage, touch issues.',
    hubHeading: 'Can I Ignore These Screen Problems?',
    seoTitle: 'Phone Screen Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone screen problems sorted by how urgent they actually are — from a small stable crack to display damage that means stop using it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'phones',
    slug: 'charging',
    name: 'Charging',
    singularName: 'Charging',
    canonicalPath: '/technology/phones/charging/',
    shortDescription: 'Cables, ports, chargers and charging faults.',
    hubHeading: 'Can I Ignore These Phone Charging Problems?',
    seoTitle: 'Phone Charging Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone charging problems sorted by how urgent they are — from slow charging you can live with to a frayed cable that needs replacing today.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'batteries',
    name: 'Batteries',
    singularName: 'Battery',
    canonicalPath: '/technology/computers/batteries/',
    shortDescription: 'Swelling, drain speed, charging health.',
    hubHeading: 'Can I Ignore These Battery Problems?',
    seoTitle: 'Laptop Battery Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop battery problems sorted by how urgent they actually are — from slow capacity loss to swelling that means stop using it now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'chargers',
    name: 'Chargers',
    singularName: 'Charger',
    canonicalPath: '/technology/computers/chargers/',
    shortDescription: 'Heat, damaged cables, charging problems.',
    hubHeading: 'Can I Ignore These Charger Problems?',
    seoTitle: 'Laptop Charger Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop charger problems sorted by how urgent they actually are — from normal operating warmth to damage that means replace it now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'food-storage',
    slug: 'frozen-food',
    name: 'Frozen Food',
    singularName: 'Frozen Food',
    canonicalPath: '/food-kitchen/food-storage/frozen-food/',
    shortDescription: 'Freezer burn, thawing, refreezing.',
    hubHeading: 'Can I Ignore These Frozen-Food Problems?',
    seoTitle: 'Frozen Food: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Frozen-food questions sorted by how urgent they actually are — from freezer burn you can ignore to temperature exposure that means discard it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'food-storage',
    slug: 'pantry',
    name: 'Pantry',
    singularName: 'Pantry',
    canonicalPath: '/food-kitchen/food-storage/pantry/',
    shortDescription: 'Cans, jars, dates and shelf-stable food.',
    hubHeading: 'Can I Ignore These Pantry Problems?',
    seoTitle: 'Pantry and Canned Food: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Canned and shelf-stable food questions sorted by how urgent they are — from a shallow dent that is fine to a bulging can you must not open.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigeration',
    slug: 'food-safety',
    name: 'Food Safety',
    singularName: 'Food Safety',
    canonicalPath: '/food-kitchen/refrigeration/food-safety/',
    shortDescription: 'Temperature exposure, spoilage, discard guidance.',
    hubHeading: 'Can I Ignore These Food-Safety Problems?',
    seoTitle: 'Refrigerator Food Safety: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator food-safety questions sorted by how urgent they actually are — from a briefly open door to perishables that must be thrown out.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  ...(
    [
      // slug, name, description, sortOrder, attributive form used in prose
      ['battery-and-electrical', 'Battery & Electrical', 'Starting, charging, lights, sensors.', 40, 'Electrical'],
      ['cooling', 'Cooling', 'Coolant, radiator, thermostat, overheating.', 50, 'Cooling'],
      ['suspension', 'Suspension', 'Shocks, springs, bushings, ride quality.', 70, 'Suspension'],
      ['steering', 'Steering', 'Play, pulling, noises, alignment.', 80, 'Steering'],
      ['transmission', 'Transmission', 'Shifting, slipping, fluid, noises.', 90, 'Transmission'],
      ['lights', 'Lights', 'Bulbs, alignment, warning indicators.', 110, 'Light'],
      ['body', 'Body', 'Rust, dents, seals, trim.', 130, 'Body'],
    ] as const
  ).map(
    ([slug, name, shortDescription, sortOrder, singularName]): SystemSeed => ({
      objectSlug: 'cars',
      slug,
      name,
      singularName,
      canonicalPath: `/cars/${slug}/`,
      shortDescription,
      sortOrder,
      status: 'draft',
      indexable: false,
    }),
  ),
];
