import type { DomainSeed, ObjectCategorySeed, SystemSeed } from './types';

/**
 * DOMAIN -> OBJECT -> SYSTEM.
 *
 * Note what is NOT here: a "Life" level above Mobility. Every problem on this
 * site is a life problem, so the word carries no information and would earn no
 * URL segment, no useful hub and no clarity for a crawler. The taxonomy starts
 * where the first genuine distinction is.
 *
 * `status: 'draft'` means "named, reserved, not built". Draft nodes are not
 * routable and never enter the sitemap; hubs list them as plain text so the site
 * shows its real size instead of a wall of empty category pages.
 *
 * `indexable` is separate from `status` on purpose. A hub can be live and
 * linkable for humans while still being too thin to deserve a place in search
 * results. Flip it to true once the hub actually helps a searcher.
 */

export const domains: DomainSeed[] = [
  {
    slug: 'mobility',
    name: 'Mobility',
    canonicalPath: '/mobility/',
    shortDescription: 'Cars, motorcycles, bikes — anything you use to get around.',
    hubHeading: 'Mobility Problems: What Can You Ignore?',
    seoTitle: 'Mobility Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the car, motorcycle and bike problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 10,
    status: 'published',
    // One published problem beneath it. Not yet a page worth ranking.
    indexable: false,
  },
  // Reserved top-level domains. Named so the shape of the site is visible, drafts
  // so none of them becomes an empty indexed page.
  {
    slug: 'home',
    name: 'Home',
    canonicalPath: '/home/',
    shortDescription: 'Plumbing, electrical, HVAC, roof, structure.',
    hubHeading: 'Home Problems: What Can You Ignore?',
    seoTitle: 'Home Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the household plumbing and electrical problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'appliances',
    name: 'Appliances',
    canonicalPath: '/appliances/',
    shortDescription: 'Fridges, dishwashers, washers, dryers, coffee machines.',
    hubHeading: 'Appliance Problems: What Can You Ignore?',
    seoTitle: 'Appliance Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the appliance problems people put off — the noises, frost and drainage faults that can wait, and the ones that need dealing with now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'food-kitchen',
    name: 'Food & Kitchen',
    canonicalPath: '/food-kitchen/',
    shortDescription: 'Food storage, freezer and refrigerator safety.',
    hubHeading: 'Food & Kitchen: What Can You Ignore?',
    seoTitle: 'Food & Kitchen: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on food-storage and refrigeration questions — what is still safe to eat, what to check first, and what to throw out.',
    sortOrder: 35,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'tech',
    name: 'Technology',
    canonicalPath: '/technology/',
    shortDescription: 'Computers, phones, routers, storage, updates.',
    hubHeading: 'Technology Problems: What Can You Ignore?',
    seoTitle: 'Technology Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on phone and computer problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'pets',
    name: 'Pets',
    canonicalPath: '/pets/',
    shortDescription: 'Dogs and cats — eating, digestion, breathing, litter box habits and behavior changes that suddenly look wrong.',
    hubHeading: 'Pet Problems: What Can You Ignore?',
    seoTitle: 'Pet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the dog and cat symptoms owners put off — what is safe to watch overnight, what needs a vet call, and what means go now.',
    sortOrder: 45,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'babies',
    name: 'Babies',
    canonicalPath: '/babies/',
    shortDescription:
      'Feeding, breathing, sleep and nappies — the things new parents check twenty times a day and cannot tell apart from a problem.',
    hubHeading: 'Baby Problems: What Can You Ignore?',
    seoTitle: 'Baby Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on what newborns do that worries their parents — what is normal, what is worth a call to the pediatrician, and what means go now.',
    sortOrder: 46,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'travel',
    name: 'Travel',
    canonicalPath: '/travel/',
    shortDescription:
      'Passports, tickets, connections, luggage, hotel rooms and rental cars — the things that go wrong on the way.',
    hubHeading: 'Travel Problems: What Can You Ignore?',
    seoTitle: 'Travel Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the travel problems people spot too late — what still lets you fly, what to fix before you go, and what to raise at the desk now.',
    sortOrder: 48,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'garden-and-outdoors',
    name: 'Garden & Outdoors',
    canonicalPath: '/garden-and-outdoors/',
    shortDescription: 'Lawn, trees, plants, pools, outdoor equipment.',
    sortOrder: 50,
    status: 'draft',
    indexable: false,
  },
  {
    slug: 'personal-gear',
    name: 'Personal Gear',
    canonicalPath: '/personal-gear/',
    shortDescription: 'Shoes, watches, cameras, sports and outdoor kit.',
    sortOrder: 60,
    status: 'draft',
    indexable: false,
  },
];

export const objectCategories: ObjectCategorySeed[] = [
  {
    domainSlug: 'mobility',
    slug: 'cars',
    name: 'Cars',
    singularName: 'Car',
    // Deliberately NOT /mobility/cars/. Mobility is a useful hub and a useful
    // breadcrumb; it is not a useful URL segment.
    canonicalPath: '/cars/',
    shortDescription: 'Warning lights, noises, leaks and the maintenance you have been putting off.',
    hubHeading: 'Car Problems: What Can You Ignore?',
    seoTitle: 'Car Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Straight verdicts on common car problems. Find out which ones can wait, which ones cannot, and what actually happens if you keep driving.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'motorcycles',
    name: 'Motorcycles',
    canonicalPath: '/motorcycles/',
    shortDescription: 'Chain, tires, brakes, fluids.',
    sortOrder: 20,
    status: 'draft',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'bicycles',
    name: 'Bicycles',
    singularName: 'Bike',
    canonicalPath: '/bicycles/',
    shortDescription: 'Helmets, drivetrain, brakes, tires, bearings.',
    hubHeading: 'Bike Problems: What Can You Ignore?',
    seoTitle: 'Bike Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Bicycle problems sorted by how urgent they actually are — starting with the safety gear, where the answer is rarely a matter of opinion.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'e-bikes-and-scooters',
    name: 'E-bikes & Scooters',
    canonicalPath: '/e-bikes-and-scooters/',
    shortDescription: 'Batteries, motors, brakes, firmware.',
    sortOrder: 40,
    status: 'draft',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'plumbing',
    name: 'Plumbing',
    singularName: 'Plumbing',
    canonicalPath: '/home/plumbing/',
    shortDescription: 'Drains, toilets, leaks, water pressure.',
    hubHeading: 'Plumbing Problems: What Can You Ignore?',
    seoTitle: 'Plumbing Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household plumbing problems sorted by how urgent they actually are — from a slow drain you can watch to leaks that need attention now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'electrical',
    name: 'Electrical',
    singularName: 'Electrical',
    canonicalPath: '/home/electrical/',
    shortDescription: 'Outlets, switches, lighting, wiring.',
    hubHeading: 'Electrical Problems: What Can You Ignore?',
    seoTitle: 'Electrical Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household electrical problems sorted by how urgent they actually are — from a flickering light you can watch to warning signs that need an electrician now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'safety',
    name: 'Home Safety',
    singularName: 'Home Safety',
    canonicalPath: '/home/safety/',
    shortDescription: 'Smoke and CO alarms, extinguishers, detectors.',
    hubHeading: 'Home Safety: What Can You Ignore?',
    seoTitle: 'Home Safety Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Home safety-device problems sorted by how urgent they actually are — from a chirping smoke alarm to alarm patterns that mean get out now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'structure',
    name: 'Structure',
    singularName: 'Structure',
    canonicalPath: '/home/structure/',
    shortDescription: 'Windows, walls, ceilings, foundation, damp and rot.',
    hubHeading: 'Home Structure: What Can You Ignore?',
    seoTitle: 'Window and Damp Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Window and damp problems sorted by how urgent they actually are — starting with the mold that shows up on a frame every winter.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'hvac',
    name: 'HVAC',
    singularName: 'HVAC',
    canonicalPath: '/home/hvac/',
    shortDescription: 'Air conditioning, furnaces and heating.',
    hubHeading: 'HVAC Problems: What Can You Ignore?',
    seoTitle: 'HVAC Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Heating and air conditioning problems sorted by how urgent they actually are — from normal seasonal quirks to warning signs that need a technician now.',
    sortOrder: 25,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'roof',
    name: 'Roof',
    singularName: 'Roof',
    canonicalPath: '/home/roof/',
    shortDescription: 'Shingles, leaks, gutters and roof damage.',
    hubHeading: 'Roof Problems: What Can You Ignore?',
    seoTitle: 'Roof Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Roof problems sorted by how urgent they actually are — from a single missing shingle to damage that means call a roofer now.',
    sortOrder: 45,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'food-kitchen',
    slug: 'food-storage',
    name: 'Food Storage',
    singularName: 'Food Storage',
    canonicalPath: '/food-kitchen/food-storage/',
    shortDescription: 'Freezer burn, expiration, spoilage signs.',
    hubHeading: 'Food Storage: What Can You Ignore?',
    seoTitle: 'Food Storage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Food-storage questions sorted by how urgent they actually are — from freezer burn you can ignore to spoilage signs that mean throw it out.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'food-kitchen',
    slug: 'refrigeration',
    name: 'Refrigeration',
    singularName: 'Refrigeration',
    canonicalPath: '/food-kitchen/refrigeration/',
    shortDescription: 'Temperature, power loss, food safety after a fridge problem.',
    hubHeading: 'Refrigeration Problems: What Can You Ignore?',
    seoTitle: 'Refrigeration Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator and freezer questions sorted by how urgent they actually are — from a brief door-open mishap to food that needs to be discarded.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'phones',
    name: 'Phones',
    singularName: 'Phone',
    canonicalPath: '/technology/phones/',
    shortDescription: 'Screens, batteries, charging, water damage.',
    hubHeading: 'Phone Problems: What Can You Ignore?',
    seoTitle: 'Phone Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone problems sorted by how urgent they actually are — from a small screen crack you can watch to damage that means stop using it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'computers',
    name: 'Computers',
    singularName: 'Computer',
    canonicalPath: '/technology/computers/',
    shortDescription: 'Batteries, chargers, overheating, performance.',
    hubHeading: 'Computer Problems: What Can You Ignore?',
    seoTitle: 'Computer Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop and computer problems sorted by how urgent they actually are — from a warm charger you can ignore to a battery that means stop using it.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'storage',
    name: 'Storage',
    singularName: 'Storage',
    canonicalPath: '/technology/storage/',
    shortDescription: 'Hard drives, SSDs, external drives and storage space.',
    hubHeading: 'Storage Problems: What Can You Ignore?',
    seoTitle: 'Storage Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Storage problems sorted by how urgent they actually are — from a full drive to a clicking hard drive that means back up now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'networking',
    name: 'Networking',
    singularName: 'Network',
    canonicalPath: '/technology/networking/',
    shortDescription: 'Wi-Fi, routers and internet connectivity.',
    hubHeading: 'Networking Problems: What Can You Ignore?',
    seoTitle: 'Networking Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Networking problems sorted by how urgent they actually are — from a device that needs a reconnect to a connection worth troubleshooting today.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'software',
    name: 'Software',
    singularName: 'Software',
    canonicalPath: '/technology/software/',
    shortDescription: 'Updates, crashes and browser security warnings.',
    hubHeading: 'Software Problems: What Can You Ignore?',
    seoTitle: 'Software Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Software problems sorted by how urgent they actually are — from an update you can postpone to a security warning worth stopping for.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'refrigerators',
    name: 'Refrigerators',
    singularName: 'Refrigerator',
    canonicalPath: '/appliances/refrigerators/',
    shortDescription: 'Noises, frost, ice buildup and cooling faults.',
    hubHeading: 'Refrigerator Problems: What Can You Ignore?',
    seoTitle: 'Refrigerator Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator and freezer faults sorted by how urgent they actually are — from the normal sound of a working compressor to signs of a real fault.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'dishwashers',
    name: 'Dishwashers',
    singularName: 'Dishwasher',
    canonicalPath: '/appliances/dishwashers/',
    shortDescription: 'Draining, standing water, smells and leaks.',
    hubHeading: 'Dishwasher Problems: What Can You Ignore?',
    seoTitle: 'Dishwasher Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dishwasher problems sorted by how urgent they actually are — from a little water left in the bottom to a machine backing up into the sink.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'microwaves',
    name: 'Microwaves',
    singularName: 'Microwave',
    canonicalPath: '/appliances/microwaves/',
    shortDescription: 'Sparking, burning smells, door seals and interior damage.',
    hubHeading: 'Microwave Problems: What Can You Ignore?',
    seoTitle: 'Microwave Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Microwave problems sorted by how urgent they actually are — from a stain that is only cosmetic to sparking that means stop using it now.',
    sortOrder: 25,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'garbage-disposals',
    name: 'Garbage Disposals',
    singularName: 'Garbage Disposal',
    canonicalPath: '/appliances/garbage-disposals/',
    shortDescription: 'Jams, hums, clogs and things that fell in.',
    hubHeading: 'Garbage Disposal Problems: What Can You Ignore?',
    seoTitle: 'Garbage Disposal Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Garbage disposal problems sorted by how urgent they actually are — starting with the hum that means the motor is stuck and the power should be off.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'stoves-and-ovens',
    name: 'Stoves & Ovens',
    singularName: 'Stove',
    canonicalPath: '/appliances/stoves-and-ovens/',
    shortDescription: 'Gas burners, flame color, igniters and oven faults.',
    hubHeading: 'Stove and Oven Problems: What Can You Ignore?',
    seoTitle: 'Stove and Oven Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Stove and oven problems sorted by how urgent they actually are — from an igniter that clicks a few times to a burner flame worth checking today.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'washing-machines',
    name: 'Washing Machines',
    singularName: 'Washing Machine',
    canonicalPath: '/appliances/washing-machines/',
    shortDescription: 'Vibration, balance, noise and drum problems.',
    hubHeading: 'Washing Machine Problems: What Can You Ignore?',
    seoTitle: 'Washing Machine Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Washing machine problems sorted by how urgent they actually are — from a load that just needs rebalancing to shaking that means stop the cycle.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'dryers',
    name: 'Dryers',
    singularName: 'Dryer',
    canonicalPath: '/appliances/dryers/',
    shortDescription: 'Vent restriction, drying performance and burning smells.',
    hubHeading: 'Dryer Problems: What Can You Ignore?',
    seoTitle: 'Dryer Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dryer problems sorted by how urgent they actually are — from a slower cycle worth a lint check to a burning smell that means stop and unplug it.',
    sortOrder: 60,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'pets',
    slug: 'dogs',
    name: 'Dogs',
    singularName: 'Dog',
    canonicalPath: '/pets/dogs/',
    shortDescription: 'Eating, digestion, breathing, skin and behavior changes in dogs.',
    hubHeading: 'Dog Problems: What Can You Ignore?',
    seoTitle: 'Dog Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on common dog symptoms — what is safe to watch at home, what needs a vet call, and what means go now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'pets',
    slug: 'cats',
    name: 'Cats',
    singularName: 'Cat',
    canonicalPath: '/pets/cats/',
    shortDescription: 'Eating, digestion, breathing, litter box habits and behavior changes in cats.',
    hubHeading: 'Cat Problems: What Can You Ignore?',
    seoTitle: 'Cat Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on common cat symptoms — what is safe to watch at home, what needs a vet call, and what means go now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },

  /* Babies.
   *
   * `newborns` rather than a bare `babies` object, because the answer to almost
   * every question here turns on age: the same breathing, the same gap between
   * feeds and the same nappy mean different things at three weeks and at nine
   * months. Reserving the distinction now leaves room for `infants` and
   * `toddlers` beside it instead of one object that has to hedge every verdict. */
  {
    domainSlug: 'babies',
    slug: 'newborns',
    name: 'Newborns',
    singularName: 'Newborn',
    canonicalPath: '/babies/newborns/',
    shortDescription: 'The first weeks — feeding, breathing sounds, sleep and nappies.',
    hubHeading: 'Newborn Problems: What Can You Ignore?',
    seoTitle: 'Newborn Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on what a newborn does that worries new parents — what is normal for the first weeks, and what means call the pediatrician.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },

  /* Travel.
   *
   * Split by what the traveller is holding when the doubt hits — a document, a
   * booking, a bag, a room, a rented car — rather than by trip stage. Stage
   * ("before you go" / "at the airport") would put a damaged passport and an
   * expiring one in different places, which is exactly where a reader looks for
   * them together. */
  {
    domainSlug: 'travel',
    slug: 'travel-documents',
    name: 'Travel Documents',
    singularName: 'Travel Document',
    canonicalPath: '/travel/documents/',
    shortDescription: 'Passports and the paperwork that decides whether you board at all.',
    hubHeading: 'Travel Document Problems: What Can You Ignore?',
    seoTitle: 'Passport and Travel Document Problems | Can I Ignore It',
    metaDescription:
      'Verdicts on passport and travel document problems — what still gets you on the plane, and what has to be fixed before you leave.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'travel',
    slug: 'air-travel',
    name: 'Air Travel',
    singularName: 'Air Travel',
    canonicalPath: '/travel/air-travel/',
    shortDescription: 'Tickets, boarding passes and connections.',
    hubHeading: 'Air Travel Problems: What Can You Ignore?',
    seoTitle: 'Airline Ticket and Boarding Problems | Can I Ignore It',
    metaDescription:
      'Verdicts on ticket, boarding pass and connection problems — what the airline will sort out at the desk, and what to fix before you fly.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'travel',
    slug: 'luggage',
    name: 'Luggage',
    singularName: 'Luggage',
    canonicalPath: '/travel/luggage/',
    shortDescription: 'Suitcases, checked bags and the tags attached to them.',
    hubHeading: 'Luggage Problems: What Can You Ignore?',
    seoTitle: 'Suitcase and Checked Baggage Problems | Can I Ignore It',
    metaDescription:
      'Verdicts on suitcase damage and checked baggage problems — what will survive the trip, and what to raise before the bag goes down the belt.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'travel',
    slug: 'lodging',
    name: 'Lodging',
    singularName: 'Lodging',
    canonicalPath: '/travel/lodging/',
    shortDescription: 'Hotel and rental rooms, and what to do about the state of one.',
    hubHeading: 'Hotel Room Problems: What Can You Ignore?',
    seoTitle: 'Hotel Room Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on what you find in a hotel room — what is worth a night, what means ask for another room, and what means do not unpack.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'travel',
    slug: 'rental-cars',
    name: 'Rental Cars',
    singularName: 'Rental Car',
    canonicalPath: '/travel/rental-cars/',
    shortDescription: 'Pickup, damage and the argument at drop-off.',
    hubHeading: 'Rental Car Problems: What Can You Ignore?',
    seoTitle: 'Rental Car Damage and Return Problems | Can I Ignore It',
    metaDescription:
      'Verdicts on rental car damage and return disputes — what to photograph before you drive off, and what you will be billed for if you say nothing.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
];

/**
 * The System level is what stops a large site collapsing. Fifty problems can sit
 * directly under "Cars" and still be navigable; five hundred cannot.
 */
export const systems: SystemSeed[] = [
  {
    objectSlug: 'cars',
    slug: 'tires',
    name: 'Tires',
    singularName: 'Tire',
    canonicalPath: '/cars/tires/',
    shortDescription: 'Pressure, wear, punctures, age and damage.',
    hubHeading: 'Can I Ignore These Tire Problems?',
    seoTitle: 'Tire Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Tire problems sorted by how urgent they actually are — from the ones you can leave a while to the ones that mean stop driving.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'exhaust',
    name: 'Exhaust',
    singularName: 'Exhaust',
    canonicalPath: '/cars/exhaust/',
    shortDescription: 'Noise, smell, emissions, corrosion.',
    hubHeading: 'Can I Ignore These Exhaust Problems?',
    seoTitle: 'Exhaust Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Exhaust problems sorted by how urgent they actually are — from normal condensation you can ignore to leaks and warning signs that need attention.',
    sortOrder: 100,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'engine',
    name: 'Engine',
    singularName: 'Engine',
    canonicalPath: '/cars/engine/',
    shortDescription: 'Warning lights, oil, noises, misfires.',
    hubHeading: 'Can I Ignore These Engine Problems?',
    seoTitle: 'Engine Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Engine problems sorted by how urgent they actually are — from normal cold-start behavior you can ignore to warning signs that need attention.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'brakes',
    name: 'Brakes',
    singularName: 'Brake',
    canonicalPath: '/cars/brakes/',
    shortDescription: 'Pads, discs, fluid, noises.',
    hubHeading: 'Can I Ignore These Brake Problems?',
    seoTitle: 'Brake Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Brake problems sorted by how urgent they actually are — from harmless noise you can ignore to warning signs that need attention.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'fluids',
    name: 'Fluids',
    singularName: 'Fluid',
    canonicalPath: '/cars/fluids/',
    shortDescription: 'Oil, coolant, brake, transmission, washer.',
    hubHeading: 'Can I Ignore These Fluid Problems?',
    seoTitle: 'Fluid Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Car fluid problems sorted by how urgent they actually are — from a small drip you can watch to leaks and warnings that need attention.',
    sortOrder: 60,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'glass',
    name: 'Glass',
    singularName: 'Glass',
    canonicalPath: '/cars/glass/',
    shortDescription: 'Chips, cracks, wipers, visibility.',
    hubHeading: 'Can I Ignore These Glass Problems?',
    seoTitle: 'Glass Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Car glass problems sorted by how urgent they actually are — from a small chip you can watch to cracks and damage that need attention.',
    sortOrder: 120,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'bicycles',
    slug: 'helmets',
    name: 'Helmets',
    singularName: 'Helmet',
    canonicalPath: '/bicycles/helmets/',
    shortDescription: 'Crash damage, cracks, age, fit and straps.',
    hubHeading: 'Can I Ignore These Helmet Problems?',
    seoTitle: 'Bike Helmet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Bike helmet questions sorted by how urgent they are — from a scuffed shell that is fine to damage that means the helmet is finished.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'drains',
    name: 'Drains',
    singularName: 'Drain',
    canonicalPath: '/home/plumbing/drains/',
    shortDescription: 'Slow drains, clogs, gurgling, backups.',
    hubHeading: 'Can I Ignore These Drain Problems?',
    seoTitle: 'Drain Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Drain problems sorted by how urgent they actually are — from a slightly slow sink to a sewer backup that needs a plumber now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'toilets',
    name: 'Toilets',
    singularName: 'Toilet',
    canonicalPath: '/home/plumbing/toilets/',
    shortDescription: 'Running toilets, clogs, leaks, flushing problems.',
    hubHeading: 'Can I Ignore These Toilet Problems?',
    seoTitle: 'Toilet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Toilet problems sorted by how urgent they actually are — from a briefly running tank to a bowl that is about to overflow.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'leaks',
    name: 'Leaks',
    singularName: 'Leak',
    canonicalPath: '/home/plumbing/leaks/',
    shortDescription: 'Under-sink leaks, pipe leaks, water damage.',
    hubHeading: 'Can I Ignore These Leaks?',
    seoTitle: 'Plumbing Leaks: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household leaks sorted by how urgent they actually are — from a drip you can watch to a supply line that needs the water shut off now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'water-heaters',
    name: 'Water Heaters',
    singularName: 'Water Heater',
    canonicalPath: '/home/plumbing/water-heaters/',
    shortDescription: 'Leaks, no hot water, strange noises and age.',
    hubHeading: 'Can I Ignore These Water Heater Problems?',
    seoTitle: 'Water Heater Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Water heater problems sorted by how urgent they actually are — from a damp fitting you can watch to a leak that means shut off the water now.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'water-pressure',
    name: 'Water Pressure',
    singularName: 'Water Pressure',
    canonicalPath: '/home/plumbing/water-pressure/',
    shortDescription: 'Low pressure, sudden drops and pressure that varies by fixture.',
    hubHeading: 'Can I Ignore These Water Pressure Problems?',
    seoTitle: 'Water Pressure Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Water pressure problems sorted by how urgent they actually are — from a single clogged aerator to a drop that points at a hidden leak.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'water-quality',
    name: 'Water Quality',
    singularName: 'Water Quality',
    canonicalPath: '/home/plumbing/water-quality/',
    shortDescription: 'Discoloration, odor, taste and safety of tap water.',
    hubHeading: 'Can I Ignore These Water Quality Problems?',
    seoTitle: 'Water Quality Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Tap water quality problems sorted by how urgent they actually are — from brief discoloration after work on the street to water you should not drink.',
    sortOrder: 60,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'pipes',
    name: 'Pipes',
    singularName: 'Pipe',
    canonicalPath: '/home/plumbing/pipes/',
    shortDescription: 'Banging, whistling, sweating and freezing supply pipes.',
    hubHeading: 'Can I Ignore These Pipe Problems?',
    seoTitle: 'Noisy and Sweating Pipes: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Pipe problems sorted by how urgent they actually are — from a bang you hear once when a valve shuts to pipes cold enough to be at risk of freezing.',
    sortOrder: 70,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'lighting',
    name: 'Lighting',
    singularName: 'Light',
    canonicalPath: '/home/electrical/lighting/',
    shortDescription: 'Flickering, bulbs, switches, fixtures.',
    hubHeading: 'Can I Ignore These Lighting Problems?',
    seoTitle: 'Lighting Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Lighting problems sorted by how urgent they actually are — from a flickering bulb to wiring warning signs that need an electrician.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'outlets',
    name: 'Outlets',
    singularName: 'Outlet',
    canonicalPath: '/home/electrical/outlets/',
    shortDescription: 'Warm outlets, loose plugs, sparking, wiring.',
    hubHeading: 'Can I Ignore These Outlet Problems?',
    seoTitle: 'Outlet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Electrical outlet problems sorted by how urgent they actually are — from a mildly warm plug to a receptacle that needs to stay unused.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'breakers',
    name: 'Breakers',
    singularName: 'Breaker',
    canonicalPath: '/home/electrical/breakers/',
    shortDescription: 'Tripping, resetting, overloaded circuits and panel issues.',
    hubHeading: 'Can I Ignore These Circuit Breaker Problems?',
    seoTitle: 'Circuit Breaker Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Circuit breaker problems sorted by how urgent they actually are — from an occasional overload trip to a breaker that needs an electrician now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'safety',
    slug: 'alarms',
    name: 'Alarms',
    singularName: 'Alarm',
    canonicalPath: '/home/safety/alarms/',
    shortDescription: 'Smoke alarms, CO alarms, chirps and false alarms.',
    hubHeading: 'Can I Ignore These Alarm Problems?',
    seoTitle: 'Smoke and CO Alarm Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Smoke and carbon monoxide alarm problems sorted by how urgent they are — from a low-battery chirp to the patterns that mean leave the house.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'walls',
    name: 'Walls',
    singularName: 'Wall',
    canonicalPath: '/home/structure/walls/',
    shortDescription: 'Cracks, nail pops, bulges and stains in drywall and plaster.',
    hubHeading: 'Can I Ignore These Wall Problems?',
    seoTitle: 'Wall and Drywall Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Wall and drywall problems sorted by how urgent they actually are — from a hairline crack that comes back every winter to one that is still opening.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'windows',
    name: 'Windows',
    singularName: 'Window',
    canonicalPath: '/home/structure/windows/',
    shortDescription: 'Condensation, mold, drafts, rotten frames.',
    hubHeading: 'Can I Ignore These Window Problems?',
    seoTitle: 'Window Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Window problems sorted by how urgent they actually are — from winter condensation to mold and rot that has reached the wall behind the frame.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'ceilings',
    name: 'Ceilings',
    singularName: 'Ceiling',
    canonicalPath: '/home/structure/ceilings/',
    shortDescription: 'Water stains, sagging, cracks and popcorn ceiling damage.',
    hubHeading: 'Can I Ignore These Ceiling Problems?',
    seoTitle: 'Ceiling Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Ceiling problems sorted by how urgent they actually are — from an old dry stain you can watch to active water damage that needs attention now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'foundation',
    name: 'Foundation',
    singularName: 'Foundation',
    canonicalPath: '/home/structure/foundation/',
    shortDescription: 'Cracks, settling, water intrusion and structural warning signs.',
    hubHeading: 'Can I Ignore These Foundation Problems?',
    seoTitle: 'Foundation Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Foundation problems sorted by how urgent they actually are — from a hairline crack that is normal settling to signs that need a structural engineer now.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'hvac',
    slug: 'air-conditioning',
    name: 'Air Conditioning',
    singularName: 'Air Conditioner',
    canonicalPath: '/home/hvac/air-conditioning/',
    shortDescription: 'Leaks, poor cooling, noises and drainage issues.',
    hubHeading: 'Can I Ignore These Air Conditioner Problems?',
    seoTitle: 'Air Conditioner Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Air conditioner problems sorted by how urgent they actually are — from normal condensation outside to water leaking inside that needs attention now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'hvac',
    slug: 'heating',
    name: 'Heating',
    singularName: 'Heating',
    canonicalPath: '/home/hvac/heating/',
    shortDescription: 'Furnace smells, noises, uneven heat and pilot lights.',
    hubHeading: 'Can I Ignore These Heating Problems?',
    seoTitle: 'Furnace and Heating Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Furnace and heating problems sorted by how urgent they actually are — from a brief startup smell to signs that mean turn it off and call for service.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'roof',
    slug: 'shingles',
    name: 'Shingles',
    singularName: 'Shingle',
    canonicalPath: '/home/roof/shingles/',
    shortDescription: 'Missing, curling, cracked and granule-loss shingles.',
    hubHeading: 'Can I Ignore These Shingle Problems?',
    seoTitle: 'Roof Shingle Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Roof shingle problems sorted by how urgent they actually are — from a single missing shingle to damage that means call a roofer now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'phones',
    slug: 'screens',
    name: 'Screens',
    singularName: 'Screen',
    canonicalPath: '/technology/phones/screens/',
    shortDescription: 'Cracked glass, display damage, touch issues.',
    hubHeading: 'Can I Ignore These Screen Problems?',
    seoTitle: 'Phone Screen Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone screen problems sorted by how urgent they actually are — from a small stable crack to display damage that means stop using it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'phones',
    slug: 'charging',
    name: 'Charging',
    singularName: 'Charging',
    canonicalPath: '/technology/phones/charging/',
    shortDescription: 'Cables, ports, chargers and charging faults.',
    hubHeading: 'Can I Ignore These Phone Charging Problems?',
    seoTitle: 'Phone Charging Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone charging problems sorted by how urgent they are — from slow charging you can live with to a frayed cable that needs replacing today.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'batteries',
    name: 'Batteries',
    singularName: 'Battery',
    canonicalPath: '/technology/computers/batteries/',
    shortDescription: 'Swelling, drain speed, charging health.',
    hubHeading: 'Can I Ignore These Battery Problems?',
    seoTitle: 'Laptop Battery Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop battery problems sorted by how urgent they actually are — from slow capacity loss to swelling that means stop using it now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'chargers',
    name: 'Chargers',
    singularName: 'Charger',
    canonicalPath: '/technology/computers/chargers/',
    shortDescription: 'Heat, damaged cables, charging problems.',
    hubHeading: 'Can I Ignore These Charger Problems?',
    seoTitle: 'Laptop Charger Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop charger problems sorted by how urgent they actually are — from normal operating warmth to damage that means replace it now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'crashes-and-errors',
    name: 'Crashes & Errors',
    singularName: 'Computer',
    canonicalPath: '/technology/computers/crashes-and-errors/',
    shortDescription: 'Blue screens, unexpected restarts and repeated errors.',
    hubHeading: 'Can I Ignore These Computer Crashes?',
    seoTitle: 'Computer Crashes and Errors: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Computer crashes and errors sorted by how urgent they actually are — from a one-time restart to a repeated error worth investigating.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'fans-and-cooling',
    name: 'Fans & Cooling',
    singularName: 'Computer',
    canonicalPath: '/technology/computers/fans-and-cooling/',
    shortDescription: 'Constant fan noise, dust, airflow and overheating.',
    hubHeading: 'Can I Ignore This Laptop Fan Noise?',
    seoTitle: 'Laptop Fan and Cooling: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop fan and cooling problems sorted by how urgent they actually are — from normal load noise to airflow worth checking today.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'displays',
    name: 'Displays',
    singularName: 'Display',
    canonicalPath: '/technology/computers/displays/',
    shortDescription: 'Stuck and dead pixels, flicker, lines and backlight problems.',
    hubHeading: 'Can I Ignore These Monitor Problems?',
    seoTitle: 'Monitor and Screen Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Monitor and laptop screen problems sorted by how urgent they actually are — from one dead pixel to a flicker that is worth acting on while under warranty.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'storage',
    slug: 'drives',
    name: 'Drives',
    singularName: 'Drive',
    canonicalPath: '/technology/storage/drives/',
    shortDescription: 'Clicking noises, failing drives and data loss risk.',
    hubHeading: 'Can I Ignore These Drive Problems?',
    seoTitle: 'Hard Drive Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Hard drive and storage device problems sorted by how urgent they actually are — from normal drive noise to clicking that means back up now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'storage',
    slug: 'storage-space',
    name: 'Storage Space',
    singularName: 'Storage',
    canonicalPath: '/technology/storage/storage-space/',
    shortDescription: 'Full storage warnings and low-space behavior.',
    hubHeading: 'Can I Ignore a Storage Warning?',
    seoTitle: 'Storage Space Warnings: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Storage space warnings sorted by how urgent they actually are — from a warning you can postpone to space that is already causing problems.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'networking',
    slug: 'wifi-and-connectivity',
    name: 'Wi-Fi & Connectivity',
    singularName: 'Connection',
    canonicalPath: '/technology/networking/wifi-and-connectivity/',
    shortDescription: 'Dropped connections, router reboots and outages.',
    hubHeading: 'Can I Ignore This Wi-Fi Problem?',
    seoTitle: 'Wi-Fi and Connectivity: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Wi-Fi and connectivity problems sorted by how urgent they actually are — from a single device reconnecting to an outage worth troubleshooting now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'software',
    slug: 'updates',
    name: 'Updates',
    singularName: 'Update',
    canonicalPath: '/technology/software/updates/',
    shortDescription: 'Feature updates, security updates and postponing them.',
    hubHeading: 'Can I Ignore This Software Update?',
    seoTitle: 'Software Updates: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Software update questions sorted by how urgent they actually are — from a feature update you can skip to a security update worth installing today.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'software',
    slug: 'browser-security',
    name: 'Browser Security',
    singularName: 'Browser',
    canonicalPath: '/technology/software/browser-security/',
    shortDescription: 'Security warnings, certificate errors and unsafe sites.',
    hubHeading: 'Can I Ignore This Browser Security Warning?',
    seoTitle: 'Browser Security Warnings: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Browser security warnings sorted by how urgent they actually are — from a harmless certificate quirk to a warning that means stop and do not enter data.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'food-storage',
    slug: 'frozen-food',
    name: 'Frozen Food',
    singularName: 'Frozen Food',
    canonicalPath: '/food-kitchen/food-storage/frozen-food/',
    shortDescription: 'Freezer burn, thawing, refreezing.',
    hubHeading: 'Can I Ignore These Frozen-Food Problems?',
    seoTitle: 'Frozen Food: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Frozen-food questions sorted by how urgent they actually are — from freezer burn you can ignore to temperature exposure that means discard it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'food-storage',
    slug: 'pantry',
    name: 'Pantry',
    singularName: 'Pantry',
    canonicalPath: '/food-kitchen/food-storage/pantry/',
    shortDescription: 'Cans, jars, dates and shelf-stable food.',
    hubHeading: 'Can I Ignore These Pantry Problems?',
    seoTitle: 'Pantry and Canned Food: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Canned and shelf-stable food questions sorted by how urgent they are — from a shallow dent that is fine to a bulging can you must not open.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigeration',
    slug: 'food-safety',
    name: 'Food Safety',
    singularName: 'Food Safety',
    canonicalPath: '/food-kitchen/refrigeration/food-safety/',
    shortDescription: 'Temperature exposure, spoilage, discard guidance.',
    hubHeading: 'Can I Ignore These Food-Safety Problems?',
    seoTitle: 'Refrigerator Food Safety: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator food-safety questions sorted by how urgent they actually are — from a briefly open door to perishables that must be thrown out.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigerators',
    slug: 'noises',
    name: 'Noises',
    singularName: 'Noise',
    canonicalPath: '/appliances/refrigerators/noises/',
    shortDescription: 'Buzzing, humming, clicking and rattling.',
    hubHeading: 'Can I Ignore These Refrigerator Noises?',
    seoTitle: 'Refrigerator Noises: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator noises sorted by how urgent they actually are — from the sounds a working fridge is supposed to make to noise that means a fault.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigerators',
    slug: 'frost-and-ice',
    name: 'Frost & Ice',
    singularName: 'Frost and Ice',
    canonicalPath: '/appliances/refrigerators/frost-and-ice/',
    shortDescription: 'Frost buildup, ice on the walls, blocked defrost drains.',
    hubHeading: 'Can I Ignore This Frost and Ice Buildup?',
    seoTitle: 'Freezer Frost and Ice: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Freezer frost and ice problems sorted by how urgent they actually are — from a thin layer you can scrape off to buildup that points at a fault.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dishwashers',
    slug: 'drainage',
    name: 'Drainage',
    singularName: 'Drainage',
    canonicalPath: '/appliances/dishwashers/drainage/',
    shortDescription: 'Standing water, slow draining, backups and smells.',
    hubHeading: 'Can I Ignore These Dishwasher Drainage Problems?',
    seoTitle: 'Dishwasher Drainage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dishwasher drainage problems sorted by how urgent they actually are — from a little water left in the sump to water backing up into the sink.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'microwaves',
    slug: 'sparking-and-damage',
    name: 'Sparking & Damage',
    singularName: 'Microwave',
    canonicalPath: '/appliances/microwaves/sparking-and-damage/',
    shortDescription: 'Sparks, burning smells, chipped interior paint, door damage.',
    hubHeading: 'Can I Ignore These Microwave Problems?',
    seoTitle: 'Microwave Sparking and Damage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Microwave sparking and interior damage sorted by how urgent they are — from a mark you can wipe off to sparks that mean unplug it and stop.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'garbage-disposals',
    slug: 'jams-and-clogs',
    name: 'Jams & Clogs',
    singularName: 'Garbage Disposal',
    canonicalPath: '/appliances/garbage-disposals/jams-and-clogs/',
    shortDescription: 'Humming without spinning, jams, slow drainage.',
    hubHeading: 'Can I Ignore These Garbage Disposal Problems?',
    seoTitle: 'Garbage Disposal Jams: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Garbage disposal jams and clogs sorted by how urgent they are — starting with the hum that means the motor is stuck and needs the power off.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'stoves-and-ovens',
    slug: 'gas-burners',
    name: 'Gas Burners',
    singularName: 'Gas Burner',
    canonicalPath: '/appliances/stoves-and-ovens/gas-burners/',
    shortDescription: 'Flame color, ignition, clicking and gas smells.',
    hubHeading: 'Can I Ignore These Gas Burner Problems?',
    seoTitle: 'Gas Burner Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Gas burner problems sorted by how urgent they actually are — from an igniter that clicks a few times to a flame worth checking the same day.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'washing-machines',
    slug: 'vibration-and-balance',
    name: 'Vibration & Balance',
    singularName: 'Washing Machine',
    canonicalPath: '/appliances/washing-machines/vibration-and-balance/',
    shortDescription: 'Shaking, walking, banging and load-balance problems.',
    hubHeading: 'Can I Ignore This Washing Machine Vibration?',
    seoTitle: 'Washing Machine Vibration: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Washing machine vibration and balance problems sorted by how urgent they actually are — from an uneven load to shaking that means stop the cycle.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dryers',
    slug: 'venting-and-heat',
    name: 'Venting & Heat',
    singularName: 'Dryer',
    canonicalPath: '/appliances/dryers/venting-and-heat/',
    shortDescription: 'Vent restriction, slow drying cycles and burning smells.',
    hubHeading: 'Can I Ignore These Dryer Venting Problems?',
    seoTitle: 'Dryer Venting and Heat: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dryer venting and heat problems sorted by how urgent they actually are — from a cycle that runs a little long to a burning smell that means stop now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'cooling',
    name: 'Cooling',
    singularName: 'Cooling',
    canonicalPath: '/cars/cooling/',
    shortDescription: 'Coolant, radiator, thermostat, overheating.',
    hubHeading: 'Can I Ignore These Cooling Problems?',
    seoTitle: 'Car Cooling Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cooling system problems sorted by how urgent they actually are — from a small coolant drip to a temperature gauge that means stop the car.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'suspension',
    name: 'Suspension',
    singularName: 'Suspension',
    canonicalPath: '/cars/suspension/',
    shortDescription: 'Shocks, springs, bushings, ride quality.',
    hubHeading: 'Can I Ignore These Suspension Problems?',
    seoTitle: 'Suspension Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Suspension problems sorted by how urgent they actually are — from a clunk over bumps to damage that changes the way the car handles.',
    sortOrder: 70,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'steering',
    name: 'Steering',
    singularName: 'Steering',
    canonicalPath: '/cars/steering/',
    shortDescription: 'Play, pulling, noises, alignment.',
    hubHeading: 'Can I Ignore These Steering Problems?',
    seoTitle: 'Steering Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Steering problems sorted by how urgent they actually are — from a pull you can live with to noises and play that need checking now.',
    sortOrder: 80,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'transmission',
    name: 'Transmission',
    singularName: 'Transmission',
    canonicalPath: '/cars/transmission/',
    shortDescription: 'Shifting, slipping, fluid, noises.',
    hubHeading: 'Can I Ignore These Transmission Problems?',
    seoTitle: 'Transmission Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Transmission problems sorted by how urgent they actually are — from a jerk when accelerating to slipping that means stop driving it.',
    sortOrder: 90,
    status: 'published',
    indexable: false,
  },
  ...(
    [
      // slug, name, description, sortOrder, attributive form used in prose
      ['battery-and-electrical', 'Battery & Electrical', 'Starting, charging, lights, sensors.', 40, 'Electrical'],
      ['lights', 'Lights', 'Bulbs, alignment, warning indicators.', 110, 'Light'],
      ['body', 'Body', 'Rust, dents, seals, trim.', 130, 'Body'],
    ] as const
  ).map(
    ([slug, name, shortDescription, sortOrder, singularName]): SystemSeed => ({
      objectSlug: 'cars',
      slug,
      name,
      singularName,
      canonicalPath: `/cars/${slug}/`,
      shortDescription,
      sortOrder,
      status: 'draft',
      indexable: false,
    }),
  ),
  // Dogs. System slugs are prefixed dog-/cat- because `scripts/seed.ts` resolves
  // systemSlug through a single flat Map — an unprefixed "digestion" would
  // collide the moment the cat system of the same name exists.
  {
    objectSlug: 'dogs',
    slug: 'dog-eating-and-drinking',
    name: 'Eating & Drinking',
    singularName: 'Eating and Drinking',
    canonicalPath: '/pets/dogs/eating-and-drinking/',
    shortDescription: 'Skipped meals, appetite loss, and drinking more or less than usual.',
    hubHeading: 'Can I Ignore These Eating and Drinking Changes?',
    seoTitle: 'Dog Eating and Drinking Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dog eating and drinking changes sorted by how urgent they actually are — from a skipped meal to appetite loss that means call the vet.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dogs',
    slug: 'dog-digestion',
    name: 'Digestion',
    singularName: 'Digestion',
    canonicalPath: '/pets/dogs/digestion/',
    shortDescription: 'Vomiting, diarrhea and other digestive upsets.',
    hubHeading: 'Can I Ignore These Digestive Problems?',
    seoTitle: 'Dog Digestion Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dog vomiting and diarrhea sorted by how urgent they actually are — from a one-off upset to signs that mean a vet visit today.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dogs',
    slug: 'dog-breathing',
    name: 'Breathing',
    singularName: 'Breathing',
    canonicalPath: '/pets/dogs/breathing/',
    shortDescription: 'Sneezing, snorting, coughing and other breathing sounds.',
    hubHeading: 'Can I Ignore These Breathing Sounds?',
    seoTitle: 'Dog Breathing Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dog breathing sounds sorted by how urgent they actually are — from a harmless snort to symptoms that mean call the vet.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dogs',
    slug: 'dog-toxins-and-foreign-objects',
    name: 'Toxins & Foreign Objects',
    singularName: 'Toxin or Foreign Object',
    canonicalPath: '/pets/dogs/toxins-and-foreign-objects/',
    shortDescription: 'Something eaten that should not have been — food, plants, objects.',
    hubHeading: 'Can I Ignore What My Dog Just Ate?',
    seoTitle: 'Dog Ate Something It Should Not Have: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'What to do when a dog eats something it should not have, sorted by how urgent it actually is — from harmless to call the vet now.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dogs',
    slug: 'dog-mobility',
    name: 'Mobility',
    singularName: 'Mobility',
    canonicalPath: '/pets/dogs/mobility/',
    shortDescription: 'Limping, stiffness and reluctance to move.',
    hubHeading: 'Can I Ignore How My Dog Is Moving?',
    seoTitle: 'Dog Limping and Stiffness: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dog limping and stiffness sorted by how urgent it actually is — from a limp that is gone by morning to the signs that mean the vet today.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dogs',
    slug: 'dog-skin-and-ears',
    name: 'Skin & Ears',
    singularName: 'Skin or Ear',
    canonicalPath: '/pets/dogs/skin-and-ears/',
    shortDescription: 'Scratching, licking, head shaking and skin irritation.',
    sortOrder: 60,
    status: 'draft',
    indexable: false,
  },
  {
    objectSlug: 'dogs',
    slug: 'dog-eyes',
    name: 'Eyes',
    singularName: 'Eye',
    canonicalPath: '/pets/dogs/eyes/',
    shortDescription: 'Discharge, redness, squinting and cloudiness.',
    sortOrder: 70,
    status: 'draft',
    indexable: false,
  },
  // Cats.
  {
    objectSlug: 'cats',
    slug: 'cat-digestion',
    name: 'Digestion',
    singularName: 'Digestion',
    canonicalPath: '/pets/cats/digestion/',
    shortDescription: 'Vomiting, diarrhea and other digestive upsets.',
    hubHeading: 'Can I Ignore These Digestive Problems?',
    seoTitle: 'Cat Digestion Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cat vomiting and diarrhea sorted by how urgent they actually are — from an occasional hairball to signs that mean a vet visit today.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-urinary-and-litter-box',
    name: 'Urinary & Litter Box',
    singularName: 'Urinary or Litter Box',
    canonicalPath: '/pets/cats/urinary-and-litter-box/',
    shortDescription: 'Straining to urinate, litter box avoidance and accidents.',
    hubHeading: 'Can I Ignore These Litter Box Problems?',
    seoTitle: 'Cat Urinary and Litter Box Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cat litter box and urinary problems sorted by how urgent they actually are — from a one-time accident to straining that means an emergency vet visit.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-breathing',
    name: 'Breathing',
    singularName: 'Breathing',
    canonicalPath: '/pets/cats/breathing/',
    shortDescription: 'Sneezing, congestion and other breathing changes.',
    hubHeading: 'Can I Ignore These Breathing Changes?',
    seoTitle: 'Cat Breathing Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cat sneezing and breathing changes sorted by how urgent they actually are — from an occasional sneeze to symptoms that mean call the vet.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-behavior-and-energy',
    name: 'Behavior & Energy',
    singularName: 'Behavior',
    canonicalPath: '/pets/cats/behavior-and-energy/',
    shortDescription: 'Sleeping more than usual, hiding, and sudden changes in activity.',
    hubHeading: 'Can I Ignore This Behavior Change?',
    seoTitle: 'Cat Behavior Changes: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cat behavior and energy changes sorted by how urgent they actually are — from normal extra sleep to a change worth a vet call.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-mobility',
    name: 'Mobility',
    singularName: 'Mobility',
    canonicalPath: '/pets/cats/mobility/',
    shortDescription: 'Limping, stiffness and reluctance to jump.',
    sortOrder: 50,
    status: 'draft',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-skin-and-coat',
    name: 'Skin & Coat',
    singularName: 'Skin or Coat',
    canonicalPath: '/pets/cats/skin-and-coat/',
    shortDescription: 'Overgrooming, hair loss and skin irritation.',
    sortOrder: 60,
    status: 'draft',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-eyes',
    name: 'Eyes',
    singularName: 'Eye',
    canonicalPath: '/pets/cats/eyes/',
    shortDescription: 'Discharge, redness, squinting and cloudiness.',
    sortOrder: 70,
    status: 'draft',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-toxins-and-foreign-objects',
    name: 'Toxins & Foreign Objects',
    singularName: 'Toxin or Foreign Object',
    canonicalPath: '/pets/cats/toxins-and-foreign-objects/',
    shortDescription: 'Something eaten that should not have been — plants, string, objects.',
    sortOrder: 80,
    status: 'draft',
    indexable: false,
  },
  {
    objectSlug: 'cats',
    slug: 'cat-eating-and-drinking',
    name: 'Eating & Drinking',
    singularName: 'Eating and Drinking',
    canonicalPath: '/pets/cats/eating-and-drinking/',
    shortDescription: 'Skipped meals, appetite loss and drinking changes.',
    hubHeading: 'Can I Ignore These Eating and Drinking Changes?',
    seoTitle: 'Cat Eating and Drinking Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cat eating and drinking changes sorted by how urgent they actually are — from one skipped meal to the appetite loss that means call the vet now.',
    sortOrder: 90,
    status: 'published',
    indexable: false,
  },

  /* Newborn systems.
   *
   * Grouped by what the parent is looking at, not by organ system: a parent
   * hearing snuffly breathing, a sneeze and a bout of hiccups experiences one
   * category ("the noises they make"), and splitting those across respiratory
   * and digestive headings would hide each page from the person looking for it.
   *
   * Every slug carries `newborn-` because `feeding`, `sneezing` and `hiccups`
   * are exactly the words a second domain will want later. */
  {
    objectSlug: 'newborns',
    slug: 'newborn-feeding',
    name: 'Feeding',
    singularName: 'Newborn Feeding',
    canonicalPath: '/babies/newborns/feeding/',
    shortDescription: 'Spitting up, missed feeds and how much is going in.',
    hubHeading: 'Can I Ignore This About My Newborn’s Feeding?',
    seoTitle: 'Newborn Feeding Worries: What Is Normal? | Can I Ignore It',
    metaDescription:
      'Newborn feeding questions sorted by how much they matter — spitting up, sleeping through a feed, and the signs that mean call someone.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'newborns',
    slug: 'newborn-breathing-and-sounds',
    name: 'Breathing & Sounds',
    singularName: 'Newborn Breathing',
    canonicalPath: '/babies/newborns/breathing-and-sounds/',
    shortDescription: 'Snuffles, sneezes, hiccups and the noises newborns make.',
    hubHeading: 'Can I Ignore This Noise My Newborn Makes?',
    seoTitle: 'Newborn Breathing Sounds: Normal or Not? | Can I Ignore It',
    metaDescription:
      'The noises newborns make, sorted by what they mean — snuffly breathing, sneezing and hiccups, and the signs of real breathing trouble.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'newborns',
    slug: 'newborn-diapers-and-digestion',
    name: 'Diapers & Digestion',
    singularName: 'Newborn Diaper',
    canonicalPath: '/babies/newborns/diapers-and-digestion/',
    shortDescription: 'How often, what colour, and when a gap is worth worrying about.',
    hubHeading: 'Can I Ignore What Is in My Newborn’s Diaper?',
    seoTitle: 'Newborn Diaper Worries: How Often Is Normal? | Can I Ignore It',
    metaDescription:
      'Newborn nappy questions sorted by urgency — how long a gap is normal, what the colours mean, and when to call the pediatrician.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'newborns',
    slug: 'newborn-head-and-skull',
    name: 'Head & Skull',
    singularName: 'Newborn Head',
    canonicalPath: '/babies/newborns/head-and-skull/',
    shortDescription: 'Head shape, flat spots, the soft spot and how the skull changes.',
    hubHeading: 'Can I Ignore My Newborn’s Head Shape?',
    seoTitle: 'Newborn Head Shape Worries: When to Ask | Can I Ignore It',
    metaDescription:
      'Newborn head and skull questions sorted by urgency — flat spots, the soft spot, and the signs a pediatrician wants to look at rather than watch.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },

  /* Travel systems.
   *
   * Slugs carry their object where a bare word would be ambiguous the moment a
   * second domain wants it — `connections` and `suitcases` are safe, but a
   * `damage` or `documents` system would be the next `noises`. */
  {
    objectSlug: 'travel-documents',
    slug: 'passports',
    name: 'Passports',
    singularName: 'Passport',
    canonicalPath: '/travel/documents/passports/',
    shortDescription: 'Expiry dates, damage and the state of the book itself.',
    hubHeading: 'Can I Ignore This Passport Problem?',
    seoTitle: 'Passport Problems: Expiry, Damage and Blank Pages | Can I Ignore It',
    metaDescription:
      'Passport problems sorted by whether they actually stop you travelling — expiry rules, physical damage, and what to fix before you book.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'air-travel',
    slug: 'tickets-and-check-in',
    name: 'Tickets & Check-In',
    singularName: 'Ticket and Check-In',
    canonicalPath: '/travel/air-travel/tickets-and-check-in/',
    shortDescription: 'Booking details, name mismatches and boarding passes.',
    hubHeading: 'Can I Ignore This Ticket Problem?',
    seoTitle: 'Airline Ticket and Boarding Pass Problems | Can I Ignore It',
    metaDescription:
      'Ticket and boarding pass problems sorted by urgency — what the desk fixes in a minute, and what has to be corrected before you get to the airport.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'air-travel',
    slug: 'connections',
    name: 'Connections',
    singularName: 'Connection',
    canonicalPath: '/travel/air-travel/connections/',
    shortDescription: 'Layovers, transfers and the time between two flights.',
    hubHeading: 'Can I Ignore This Connection Problem?',
    seoTitle: 'Flight Connection and Layover Problems | Can I Ignore It',
    metaDescription:
      'Layover and transfer problems sorted by how much time you actually need — same ticket or separate, and what changes when immigration is involved.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'luggage',
    slug: 'suitcases',
    name: 'Suitcases',
    singularName: 'Suitcase',
    canonicalPath: '/travel/luggage/suitcases/',
    shortDescription: 'Wheels, zips, handles and cracked shells.',
    hubHeading: 'Can I Ignore This Suitcase Problem?',
    seoTitle: 'Suitcase Damage: What Survives a Trip? | Can I Ignore It',
    metaDescription:
      'Suitcase damage sorted by whether it survives the trip — a hairline crack, a wobbling wheel, a failing zip, and what not to check at all.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'luggage',
    slug: 'checked-bags',
    name: 'Checked Bags',
    singularName: 'Checked Bag',
    canonicalPath: '/travel/luggage/checked-bags/',
    shortDescription: 'Tags, routing and what happens to a bag out of sight.',
    hubHeading: 'Can I Ignore This Checked Bag Problem?',
    seoTitle: 'Checked Baggage and Bag Tag Problems | Can I Ignore It',
    metaDescription:
      'Checked baggage problems sorted by how fast you have to speak up — wrong tags, routing errors, and what to settle before the bag leaves the desk.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'lodging',
    slug: 'hotel-rooms',
    name: 'Hotel Rooms',
    singularName: 'Hotel Room',
    canonicalPath: '/travel/lodging/hotel-rooms/',
    shortDescription: 'Smells, stains, pests and the state of the room you were given.',
    hubHeading: 'Can I Ignore This in My Hotel Room?',
    seoTitle: 'Hotel Room Problems: Smells, Stains and Pests | Can I Ignore It',
    metaDescription:
      'What you find in a hotel room, sorted by what to do about it — sleep on it, ask for another room, or do not put the suitcase down.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'rental-cars',
    slug: 'rental-car-damage',
    name: 'Damage & Returns',
    singularName: 'Rental Car Damage',
    canonicalPath: '/travel/rental-cars/damage-and-returns/',
    shortDescription: 'Marks found at pickup, marks found at drop-off, and who pays for them.',
    hubHeading: 'Can I Ignore This on a Rental Car?',
    seoTitle: 'Rental Car Damage: What You Get Billed For | Can I Ignore It',
    metaDescription:
      'Rental car damage sorted by what it costs you — what to photograph before driving off, what to report, and what you pay for by staying quiet.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
];
