import type { DomainSeed, ObjectCategorySeed, SystemSeed } from './types';

/**
 * DOMAIN -> OBJECT -> SYSTEM.
 *
 * Note what is NOT here: a "Life" level above Mobility. Every problem on this
 * site is a life problem, so the word carries no information and would earn no
 * URL segment, no useful hub and no clarity for a crawler. The taxonomy starts
 * where the first genuine distinction is.
 *
 * `status: 'draft'` means "named, reserved, not built". Draft nodes are not
 * routable and never enter the sitemap; hubs list them as plain text so the site
 * shows its real size instead of a wall of empty category pages.
 *
 * `indexable` is separate from `status` on purpose. A hub can be live and
 * linkable for humans while still being too thin to deserve a place in search
 * results. Flip it to true once the hub actually helps a searcher.
 */

export const domains: DomainSeed[] = [
  {
    slug: 'mobility',
    name: 'Mobility',
    canonicalPath: '/mobility/',
    shortDescription: 'Cars, motorcycles, bikes — anything you use to get around.',
    hubHeading: 'Mobility Problems: What Can You Ignore?',
    seoTitle: 'Mobility Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the car, motorcycle and bike problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 10,
    status: 'published',
    // One published problem beneath it. Not yet a page worth ranking.
    indexable: false,
  },
  // Reserved top-level domains. Named so the shape of the site is visible, drafts
  // so none of them becomes an empty indexed page.
  {
    slug: 'home',
    name: 'Home',
    canonicalPath: '/home/',
    shortDescription: 'Plumbing, electrical, HVAC, roof, structure.',
    hubHeading: 'Home Problems: What Can You Ignore?',
    seoTitle: 'Home Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the household plumbing and electrical problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'appliances',
    name: 'Appliances',
    canonicalPath: '/appliances/',
    shortDescription: 'Fridges, dishwashers, washers, dryers, coffee machines.',
    hubHeading: 'Appliance Problems: What Can You Ignore?',
    seoTitle: 'Appliance Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on the appliance problems people put off — the noises, frost and drainage faults that can wait, and the ones that need dealing with now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'food-kitchen',
    name: 'Food & Kitchen',
    canonicalPath: '/food-kitchen/',
    shortDescription: 'Food storage, freezer and refrigerator safety.',
    hubHeading: 'Food & Kitchen: What Can You Ignore?',
    seoTitle: 'Food & Kitchen: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on food-storage and refrigeration questions — what is still safe to eat, what to check first, and what to throw out.',
    sortOrder: 35,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'tech',
    name: 'Technology',
    canonicalPath: '/technology/',
    shortDescription: 'Computers, phones, routers, storage, updates.',
    hubHeading: 'Technology Problems: What Can You Ignore?',
    seoTitle: 'Technology Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Verdicts on phone and computer problems people put off — what is safe to leave, what needs dealing with, and what happens if you wait.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    slug: 'garden-and-outdoors',
    name: 'Garden & Outdoors',
    canonicalPath: '/garden-and-outdoors/',
    shortDescription: 'Lawn, trees, plants, pools, outdoor equipment.',
    sortOrder: 50,
    status: 'draft',
    indexable: false,
  },
  {
    slug: 'personal-gear',
    name: 'Personal Gear',
    canonicalPath: '/personal-gear/',
    shortDescription: 'Shoes, watches, cameras, sports and outdoor kit.',
    sortOrder: 60,
    status: 'draft',
    indexable: false,
  },
];

export const objectCategories: ObjectCategorySeed[] = [
  {
    domainSlug: 'mobility',
    slug: 'cars',
    name: 'Cars',
    singularName: 'Car',
    // Deliberately NOT /mobility/cars/. Mobility is a useful hub and a useful
    // breadcrumb; it is not a useful URL segment.
    canonicalPath: '/cars/',
    shortDescription: 'Warning lights, noises, leaks and the maintenance you have been putting off.',
    hubHeading: 'Car Problems: What Can You Ignore?',
    seoTitle: 'Car Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Straight verdicts on common car problems. Find out which ones can wait, which ones cannot, and what actually happens if you keep driving.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'motorcycles',
    name: 'Motorcycles',
    canonicalPath: '/motorcycles/',
    shortDescription: 'Chain, tires, brakes, fluids.',
    sortOrder: 20,
    status: 'draft',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'bicycles',
    name: 'Bicycles',
    singularName: 'Bike',
    canonicalPath: '/bicycles/',
    shortDescription: 'Helmets, drivetrain, brakes, tires, bearings.',
    hubHeading: 'Bike Problems: What Can You Ignore?',
    seoTitle: 'Bike Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Bicycle problems sorted by how urgent they actually are — starting with the safety gear, where the answer is rarely a matter of opinion.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'mobility',
    slug: 'e-bikes-and-scooters',
    name: 'E-bikes & Scooters',
    canonicalPath: '/e-bikes-and-scooters/',
    shortDescription: 'Batteries, motors, brakes, firmware.',
    sortOrder: 40,
    status: 'draft',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'plumbing',
    name: 'Plumbing',
    singularName: 'Plumbing',
    canonicalPath: '/home/plumbing/',
    shortDescription: 'Drains, toilets, leaks, water pressure.',
    hubHeading: 'Plumbing Problems: What Can You Ignore?',
    seoTitle: 'Plumbing Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household plumbing problems sorted by how urgent they actually are — from a slow drain you can watch to leaks that need attention now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'electrical',
    name: 'Electrical',
    singularName: 'Electrical',
    canonicalPath: '/home/electrical/',
    shortDescription: 'Outlets, switches, lighting, wiring.',
    hubHeading: 'Electrical Problems: What Can You Ignore?',
    seoTitle: 'Electrical Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household electrical problems sorted by how urgent they actually are — from a flickering light you can watch to warning signs that need an electrician now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'safety',
    name: 'Home Safety',
    singularName: 'Home Safety',
    canonicalPath: '/home/safety/',
    shortDescription: 'Smoke and CO alarms, extinguishers, detectors.',
    hubHeading: 'Home Safety: What Can You Ignore?',
    seoTitle: 'Home Safety Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Home safety-device problems sorted by how urgent they actually are — from a chirping smoke alarm to alarm patterns that mean get out now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'structure',
    name: 'Structure',
    singularName: 'Structure',
    canonicalPath: '/home/structure/',
    shortDescription: 'Windows, walls, ceilings, foundation, damp and rot.',
    hubHeading: 'Home Structure: What Can You Ignore?',
    seoTitle: 'Window and Damp Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Window and damp problems sorted by how urgent they actually are — starting with the mold that shows up on a frame every winter.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'hvac',
    name: 'HVAC',
    singularName: 'HVAC',
    canonicalPath: '/home/hvac/',
    shortDescription: 'Air conditioning, furnaces and heating.',
    hubHeading: 'HVAC Problems: What Can You Ignore?',
    seoTitle: 'HVAC Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Heating and air conditioning problems sorted by how urgent they actually are — from normal seasonal quirks to warning signs that need a technician now.',
    sortOrder: 25,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'home',
    slug: 'roof',
    name: 'Roof',
    singularName: 'Roof',
    canonicalPath: '/home/roof/',
    shortDescription: 'Shingles, leaks, gutters and roof damage.',
    hubHeading: 'Roof Problems: What Can You Ignore?',
    seoTitle: 'Roof Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Roof problems sorted by how urgent they actually are — from a single missing shingle to damage that means call a roofer now.',
    sortOrder: 45,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'food-kitchen',
    slug: 'food-storage',
    name: 'Food Storage',
    singularName: 'Food Storage',
    canonicalPath: '/food-kitchen/food-storage/',
    shortDescription: 'Freezer burn, expiration, spoilage signs.',
    hubHeading: 'Food Storage: What Can You Ignore?',
    seoTitle: 'Food Storage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Food-storage questions sorted by how urgent they actually are — from freezer burn you can ignore to spoilage signs that mean throw it out.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'food-kitchen',
    slug: 'refrigeration',
    name: 'Refrigeration',
    singularName: 'Refrigeration',
    canonicalPath: '/food-kitchen/refrigeration/',
    shortDescription: 'Temperature, power loss, food safety after a fridge problem.',
    hubHeading: 'Refrigeration Problems: What Can You Ignore?',
    seoTitle: 'Refrigeration Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator and freezer questions sorted by how urgent they actually are — from a brief door-open mishap to food that needs to be discarded.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'phones',
    name: 'Phones',
    singularName: 'Phone',
    canonicalPath: '/technology/phones/',
    shortDescription: 'Screens, batteries, charging, water damage.',
    hubHeading: 'Phone Problems: What Can You Ignore?',
    seoTitle: 'Phone Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone problems sorted by how urgent they actually are — from a small screen crack you can watch to damage that means stop using it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'tech',
    slug: 'computers',
    name: 'Computers',
    singularName: 'Computer',
    canonicalPath: '/technology/computers/',
    shortDescription: 'Batteries, chargers, overheating, performance.',
    hubHeading: 'Computer Problems: What Can You Ignore?',
    seoTitle: 'Computer Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop and computer problems sorted by how urgent they actually are — from a warm charger you can ignore to a battery that means stop using it.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'refrigerators',
    name: 'Refrigerators',
    singularName: 'Refrigerator',
    canonicalPath: '/appliances/refrigerators/',
    shortDescription: 'Noises, frost, ice buildup and cooling faults.',
    hubHeading: 'Refrigerator Problems: What Can You Ignore?',
    seoTitle: 'Refrigerator Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator and freezer faults sorted by how urgent they actually are — from the normal sound of a working compressor to signs of a real fault.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'dishwashers',
    name: 'Dishwashers',
    singularName: 'Dishwasher',
    canonicalPath: '/appliances/dishwashers/',
    shortDescription: 'Draining, standing water, smells and leaks.',
    hubHeading: 'Dishwasher Problems: What Can You Ignore?',
    seoTitle: 'Dishwasher Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dishwasher problems sorted by how urgent they actually are — from a little water left in the bottom to a machine backing up into the sink.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'microwaves',
    name: 'Microwaves',
    singularName: 'Microwave',
    canonicalPath: '/appliances/microwaves/',
    shortDescription: 'Sparking, burning smells, door seals and interior damage.',
    hubHeading: 'Microwave Problems: What Can You Ignore?',
    seoTitle: 'Microwave Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Microwave problems sorted by how urgent they actually are — from a stain that is only cosmetic to sparking that means stop using it now.',
    sortOrder: 25,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'garbage-disposals',
    name: 'Garbage Disposals',
    singularName: 'Garbage Disposal',
    canonicalPath: '/appliances/garbage-disposals/',
    shortDescription: 'Jams, hums, clogs and things that fell in.',
    hubHeading: 'Garbage Disposal Problems: What Can You Ignore?',
    seoTitle: 'Garbage Disposal Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Garbage disposal problems sorted by how urgent they actually are — starting with the hum that means the motor is stuck and the power should be off.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    domainSlug: 'appliances',
    slug: 'stoves-and-ovens',
    name: 'Stoves & Ovens',
    singularName: 'Stove',
    canonicalPath: '/appliances/stoves-and-ovens/',
    shortDescription: 'Gas burners, flame color, igniters and oven faults.',
    hubHeading: 'Stove and Oven Problems: What Can You Ignore?',
    seoTitle: 'Stove and Oven Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Stove and oven problems sorted by how urgent they actually are — from an igniter that clicks a few times to a burner flame worth checking today.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
];

/**
 * The System level is what stops a large site collapsing. Fifty problems can sit
 * directly under "Cars" and still be navigable; five hundred cannot.
 */
export const systems: SystemSeed[] = [
  {
    objectSlug: 'cars',
    slug: 'tires',
    name: 'Tires',
    singularName: 'Tire',
    canonicalPath: '/cars/tires/',
    shortDescription: 'Pressure, wear, punctures, age and damage.',
    hubHeading: 'Can I Ignore These Tire Problems?',
    seoTitle: 'Tire Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Tire problems sorted by how urgent they actually are — from the ones you can leave a while to the ones that mean stop driving.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'exhaust',
    name: 'Exhaust',
    singularName: 'Exhaust',
    canonicalPath: '/cars/exhaust/',
    shortDescription: 'Noise, smell, emissions, corrosion.',
    hubHeading: 'Can I Ignore These Exhaust Problems?',
    seoTitle: 'Exhaust Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Exhaust problems sorted by how urgent they actually are — from normal condensation you can ignore to leaks and warning signs that need attention.',
    sortOrder: 100,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'engine',
    name: 'Engine',
    singularName: 'Engine',
    canonicalPath: '/cars/engine/',
    shortDescription: 'Warning lights, oil, noises, misfires.',
    hubHeading: 'Can I Ignore These Engine Problems?',
    seoTitle: 'Engine Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Engine problems sorted by how urgent they actually are — from normal cold-start behavior you can ignore to warning signs that need attention.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'brakes',
    name: 'Brakes',
    singularName: 'Brake',
    canonicalPath: '/cars/brakes/',
    shortDescription: 'Pads, discs, fluid, noises.',
    hubHeading: 'Can I Ignore These Brake Problems?',
    seoTitle: 'Brake Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Brake problems sorted by how urgent they actually are — from harmless noise you can ignore to warning signs that need attention.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'fluids',
    name: 'Fluids',
    singularName: 'Fluid',
    canonicalPath: '/cars/fluids/',
    shortDescription: 'Oil, coolant, brake, transmission, washer.',
    hubHeading: 'Can I Ignore These Fluid Problems?',
    seoTitle: 'Fluid Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Car fluid problems sorted by how urgent they actually are — from a small drip you can watch to leaks and warnings that need attention.',
    sortOrder: 60,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'glass',
    name: 'Glass',
    singularName: 'Glass',
    canonicalPath: '/cars/glass/',
    shortDescription: 'Chips, cracks, wipers, visibility.',
    hubHeading: 'Can I Ignore These Glass Problems?',
    seoTitle: 'Glass Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Car glass problems sorted by how urgent they actually are — from a small chip you can watch to cracks and damage that need attention.',
    sortOrder: 120,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'bicycles',
    slug: 'helmets',
    name: 'Helmets',
    singularName: 'Helmet',
    canonicalPath: '/bicycles/helmets/',
    shortDescription: 'Crash damage, cracks, age, fit and straps.',
    hubHeading: 'Can I Ignore These Helmet Problems?',
    seoTitle: 'Bike Helmet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Bike helmet questions sorted by how urgent they are — from a scuffed shell that is fine to damage that means the helmet is finished.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'drains',
    name: 'Drains',
    singularName: 'Drain',
    canonicalPath: '/home/plumbing/drains/',
    shortDescription: 'Slow drains, clogs, gurgling, backups.',
    hubHeading: 'Can I Ignore These Drain Problems?',
    seoTitle: 'Drain Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Drain problems sorted by how urgent they actually are — from a slightly slow sink to a sewer backup that needs a plumber now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'toilets',
    name: 'Toilets',
    singularName: 'Toilet',
    canonicalPath: '/home/plumbing/toilets/',
    shortDescription: 'Running toilets, clogs, leaks, flushing problems.',
    hubHeading: 'Can I Ignore These Toilet Problems?',
    seoTitle: 'Toilet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Toilet problems sorted by how urgent they actually are — from a briefly running tank to a bowl that is about to overflow.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'leaks',
    name: 'Leaks',
    singularName: 'Leak',
    canonicalPath: '/home/plumbing/leaks/',
    shortDescription: 'Under-sink leaks, pipe leaks, water damage.',
    hubHeading: 'Can I Ignore These Leaks?',
    seoTitle: 'Plumbing Leaks: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Household leaks sorted by how urgent they actually are — from a drip you can watch to a supply line that needs the water shut off now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'water-heaters',
    name: 'Water Heaters',
    singularName: 'Water Heater',
    canonicalPath: '/home/plumbing/water-heaters/',
    shortDescription: 'Leaks, no hot water, strange noises and age.',
    hubHeading: 'Can I Ignore These Water Heater Problems?',
    seoTitle: 'Water Heater Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Water heater problems sorted by how urgent they actually are — from a damp fitting you can watch to a leak that means shut off the water now.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'water-pressure',
    name: 'Water Pressure',
    singularName: 'Water Pressure',
    canonicalPath: '/home/plumbing/water-pressure/',
    shortDescription: 'Low pressure, sudden drops and pressure that varies by fixture.',
    hubHeading: 'Can I Ignore These Water Pressure Problems?',
    seoTitle: 'Water Pressure Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Water pressure problems sorted by how urgent they actually are — from a single clogged aerator to a drop that points at a hidden leak.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'plumbing',
    slug: 'water-quality',
    name: 'Water Quality',
    singularName: 'Water Quality',
    canonicalPath: '/home/plumbing/water-quality/',
    shortDescription: 'Discoloration, odor, taste and safety of tap water.',
    hubHeading: 'Can I Ignore These Water Quality Problems?',
    seoTitle: 'Water Quality Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Tap water quality problems sorted by how urgent they actually are — from brief discoloration after work on the street to water you should not drink.',
    sortOrder: 60,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'lighting',
    name: 'Lighting',
    singularName: 'Light',
    canonicalPath: '/home/electrical/lighting/',
    shortDescription: 'Flickering, bulbs, switches, fixtures.',
    hubHeading: 'Can I Ignore These Lighting Problems?',
    seoTitle: 'Lighting Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Lighting problems sorted by how urgent they actually are — from a flickering bulb to wiring warning signs that need an electrician.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'outlets',
    name: 'Outlets',
    singularName: 'Outlet',
    canonicalPath: '/home/electrical/outlets/',
    shortDescription: 'Warm outlets, loose plugs, sparking, wiring.',
    hubHeading: 'Can I Ignore These Outlet Problems?',
    seoTitle: 'Outlet Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Electrical outlet problems sorted by how urgent they actually are — from a mildly warm plug to a receptacle that needs to stay unused.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'electrical',
    slug: 'breakers',
    name: 'Breakers',
    singularName: 'Breaker',
    canonicalPath: '/home/electrical/breakers/',
    shortDescription: 'Tripping, resetting, overloaded circuits and panel issues.',
    hubHeading: 'Can I Ignore These Circuit Breaker Problems?',
    seoTitle: 'Circuit Breaker Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Circuit breaker problems sorted by how urgent they actually are — from an occasional overload trip to a breaker that needs an electrician now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'safety',
    slug: 'alarms',
    name: 'Alarms',
    singularName: 'Alarm',
    canonicalPath: '/home/safety/alarms/',
    shortDescription: 'Smoke alarms, CO alarms, chirps and false alarms.',
    hubHeading: 'Can I Ignore These Alarm Problems?',
    seoTitle: 'Smoke and CO Alarm Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Smoke and carbon monoxide alarm problems sorted by how urgent they are — from a low-battery chirp to the patterns that mean leave the house.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'windows',
    name: 'Windows',
    singularName: 'Window',
    canonicalPath: '/home/structure/windows/',
    shortDescription: 'Condensation, mold, drafts, rotten frames.',
    hubHeading: 'Can I Ignore These Window Problems?',
    seoTitle: 'Window Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Window problems sorted by how urgent they actually are — from winter condensation to mold and rot that has reached the wall behind the frame.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'ceilings',
    name: 'Ceilings',
    singularName: 'Ceiling',
    canonicalPath: '/home/structure/ceilings/',
    shortDescription: 'Water stains, sagging, cracks and popcorn ceiling damage.',
    hubHeading: 'Can I Ignore These Ceiling Problems?',
    seoTitle: 'Ceiling Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Ceiling problems sorted by how urgent they actually are — from an old dry stain you can watch to active water damage that needs attention now.',
    sortOrder: 30,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'structure',
    slug: 'foundation',
    name: 'Foundation',
    singularName: 'Foundation',
    canonicalPath: '/home/structure/foundation/',
    shortDescription: 'Cracks, settling, water intrusion and structural warning signs.',
    hubHeading: 'Can I Ignore These Foundation Problems?',
    seoTitle: 'Foundation Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Foundation problems sorted by how urgent they actually are — from a hairline crack that is normal settling to signs that need a structural engineer now.',
    sortOrder: 40,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'hvac',
    slug: 'air-conditioning',
    name: 'Air Conditioning',
    singularName: 'Air Conditioner',
    canonicalPath: '/home/hvac/air-conditioning/',
    shortDescription: 'Leaks, poor cooling, noises and drainage issues.',
    hubHeading: 'Can I Ignore These Air Conditioner Problems?',
    seoTitle: 'Air Conditioner Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Air conditioner problems sorted by how urgent they actually are — from normal condensation outside to water leaking inside that needs attention now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'hvac',
    slug: 'heating',
    name: 'Heating',
    singularName: 'Heating',
    canonicalPath: '/home/hvac/heating/',
    shortDescription: 'Furnace smells, noises, uneven heat and pilot lights.',
    hubHeading: 'Can I Ignore These Heating Problems?',
    seoTitle: 'Furnace and Heating Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Furnace and heating problems sorted by how urgent they actually are — from a brief startup smell to signs that mean turn it off and call for service.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'roof',
    slug: 'shingles',
    name: 'Shingles',
    singularName: 'Shingle',
    canonicalPath: '/home/roof/shingles/',
    shortDescription: 'Missing, curling, cracked and granule-loss shingles.',
    hubHeading: 'Can I Ignore These Shingle Problems?',
    seoTitle: 'Roof Shingle Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Roof shingle problems sorted by how urgent they actually are — from a single missing shingle to damage that means call a roofer now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'phones',
    slug: 'screens',
    name: 'Screens',
    singularName: 'Screen',
    canonicalPath: '/technology/phones/screens/',
    shortDescription: 'Cracked glass, display damage, touch issues.',
    hubHeading: 'Can I Ignore These Screen Problems?',
    seoTitle: 'Phone Screen Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone screen problems sorted by how urgent they actually are — from a small stable crack to display damage that means stop using it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'phones',
    slug: 'charging',
    name: 'Charging',
    singularName: 'Charging',
    canonicalPath: '/technology/phones/charging/',
    shortDescription: 'Cables, ports, chargers and charging faults.',
    hubHeading: 'Can I Ignore These Phone Charging Problems?',
    seoTitle: 'Phone Charging Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Phone charging problems sorted by how urgent they are — from slow charging you can live with to a frayed cable that needs replacing today.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'batteries',
    name: 'Batteries',
    singularName: 'Battery',
    canonicalPath: '/technology/computers/batteries/',
    shortDescription: 'Swelling, drain speed, charging health.',
    hubHeading: 'Can I Ignore These Battery Problems?',
    seoTitle: 'Laptop Battery Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop battery problems sorted by how urgent they actually are — from slow capacity loss to swelling that means stop using it now.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'computers',
    slug: 'chargers',
    name: 'Chargers',
    singularName: 'Charger',
    canonicalPath: '/technology/computers/chargers/',
    shortDescription: 'Heat, damaged cables, charging problems.',
    hubHeading: 'Can I Ignore These Charger Problems?',
    seoTitle: 'Laptop Charger Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Laptop charger problems sorted by how urgent they actually are — from normal operating warmth to damage that means replace it now.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'food-storage',
    slug: 'frozen-food',
    name: 'Frozen Food',
    singularName: 'Frozen Food',
    canonicalPath: '/food-kitchen/food-storage/frozen-food/',
    shortDescription: 'Freezer burn, thawing, refreezing.',
    hubHeading: 'Can I Ignore These Frozen-Food Problems?',
    seoTitle: 'Frozen Food: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Frozen-food questions sorted by how urgent they actually are — from freezer burn you can ignore to temperature exposure that means discard it.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'food-storage',
    slug: 'pantry',
    name: 'Pantry',
    singularName: 'Pantry',
    canonicalPath: '/food-kitchen/food-storage/pantry/',
    shortDescription: 'Cans, jars, dates and shelf-stable food.',
    hubHeading: 'Can I Ignore These Pantry Problems?',
    seoTitle: 'Pantry and Canned Food: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Canned and shelf-stable food questions sorted by how urgent they are — from a shallow dent that is fine to a bulging can you must not open.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigeration',
    slug: 'food-safety',
    name: 'Food Safety',
    singularName: 'Food Safety',
    canonicalPath: '/food-kitchen/refrigeration/food-safety/',
    shortDescription: 'Temperature exposure, spoilage, discard guidance.',
    hubHeading: 'Can I Ignore These Food-Safety Problems?',
    seoTitle: 'Refrigerator Food Safety: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator food-safety questions sorted by how urgent they actually are — from a briefly open door to perishables that must be thrown out.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigerators',
    slug: 'noises',
    name: 'Noises',
    singularName: 'Noise',
    canonicalPath: '/appliances/refrigerators/noises/',
    shortDescription: 'Buzzing, humming, clicking and rattling.',
    hubHeading: 'Can I Ignore These Refrigerator Noises?',
    seoTitle: 'Refrigerator Noises: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Refrigerator noises sorted by how urgent they actually are — from the sounds a working fridge is supposed to make to noise that means a fault.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'refrigerators',
    slug: 'frost-and-ice',
    name: 'Frost & Ice',
    singularName: 'Frost and Ice',
    canonicalPath: '/appliances/refrigerators/frost-and-ice/',
    shortDescription: 'Frost buildup, ice on the walls, blocked defrost drains.',
    hubHeading: 'Can I Ignore This Frost and Ice Buildup?',
    seoTitle: 'Freezer Frost and Ice: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Freezer frost and ice problems sorted by how urgent they actually are — from a thin layer you can scrape off to buildup that points at a fault.',
    sortOrder: 20,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'dishwashers',
    slug: 'drainage',
    name: 'Drainage',
    singularName: 'Drainage',
    canonicalPath: '/appliances/dishwashers/drainage/',
    shortDescription: 'Standing water, slow draining, backups and smells.',
    hubHeading: 'Can I Ignore These Dishwasher Drainage Problems?',
    seoTitle: 'Dishwasher Drainage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Dishwasher drainage problems sorted by how urgent they actually are — from a little water left in the sump to water backing up into the sink.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'microwaves',
    slug: 'sparking-and-damage',
    name: 'Sparking & Damage',
    singularName: 'Microwave',
    canonicalPath: '/appliances/microwaves/sparking-and-damage/',
    shortDescription: 'Sparks, burning smells, chipped interior paint, door damage.',
    hubHeading: 'Can I Ignore These Microwave Problems?',
    seoTitle: 'Microwave Sparking and Damage: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Microwave sparking and interior damage sorted by how urgent they are — from a mark you can wipe off to sparks that mean unplug it and stop.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'garbage-disposals',
    slug: 'jams-and-clogs',
    name: 'Jams & Clogs',
    singularName: 'Garbage Disposal',
    canonicalPath: '/appliances/garbage-disposals/jams-and-clogs/',
    shortDescription: 'Humming without spinning, jams, slow drainage.',
    hubHeading: 'Can I Ignore These Garbage Disposal Problems?',
    seoTitle: 'Garbage Disposal Jams: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Garbage disposal jams and clogs sorted by how urgent they are — starting with the hum that means the motor is stuck and needs the power off.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'stoves-and-ovens',
    slug: 'gas-burners',
    name: 'Gas Burners',
    singularName: 'Gas Burner',
    canonicalPath: '/appliances/stoves-and-ovens/gas-burners/',
    shortDescription: 'Flame color, ignition, clicking and gas smells.',
    hubHeading: 'Can I Ignore These Gas Burner Problems?',
    seoTitle: 'Gas Burner Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Gas burner problems sorted by how urgent they actually are — from an igniter that clicks a few times to a flame worth checking the same day.',
    sortOrder: 10,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'cooling',
    name: 'Cooling',
    singularName: 'Cooling',
    canonicalPath: '/cars/cooling/',
    shortDescription: 'Coolant, radiator, thermostat, overheating.',
    hubHeading: 'Can I Ignore These Cooling Problems?',
    seoTitle: 'Car Cooling Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Cooling system problems sorted by how urgent they actually are — from a small coolant drip to a temperature gauge that means stop the car.',
    sortOrder: 50,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'suspension',
    name: 'Suspension',
    singularName: 'Suspension',
    canonicalPath: '/cars/suspension/',
    shortDescription: 'Shocks, springs, bushings, ride quality.',
    hubHeading: 'Can I Ignore These Suspension Problems?',
    seoTitle: 'Suspension Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Suspension problems sorted by how urgent they actually are — from a clunk over bumps to damage that changes the way the car handles.',
    sortOrder: 70,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'steering',
    name: 'Steering',
    singularName: 'Steering',
    canonicalPath: '/cars/steering/',
    shortDescription: 'Play, pulling, noises, alignment.',
    hubHeading: 'Can I Ignore These Steering Problems?',
    seoTitle: 'Steering Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Steering problems sorted by how urgent they actually are — from a pull you can live with to noises and play that need checking now.',
    sortOrder: 80,
    status: 'published',
    indexable: false,
  },
  {
    objectSlug: 'cars',
    slug: 'transmission',
    name: 'Transmission',
    singularName: 'Transmission',
    canonicalPath: '/cars/transmission/',
    shortDescription: 'Shifting, slipping, fluid, noises.',
    hubHeading: 'Can I Ignore These Transmission Problems?',
    seoTitle: 'Transmission Problems: What Can You Ignore? | Can I Ignore It',
    metaDescription:
      'Transmission problems sorted by how urgent they actually are — from a jerk when accelerating to slipping that means stop driving it.',
    sortOrder: 90,
    status: 'published',
    indexable: false,
  },
  ...(
    [
      // slug, name, description, sortOrder, attributive form used in prose
      ['battery-and-electrical', 'Battery & Electrical', 'Starting, charging, lights, sensors.', 40, 'Electrical'],
      ['lights', 'Lights', 'Bulbs, alignment, warning indicators.', 110, 'Light'],
      ['body', 'Body', 'Rust, dents, seals, trim.', 130, 'Body'],
    ] as const
  ).map(
    ([slug, name, shortDescription, sortOrder, singularName]): SystemSeed => ({
      objectSlug: 'cars',
      slug,
      name,
      singularName,
      canonicalPath: `/cars/${slug}/`,
      shortDescription,
      sortOrder,
      status: 'draft',
      indexable: false,
    }),
  ),
];
